@testable import IvorTuning
import Testing
import XestiNumbers

struct EqualTemperamentTests {
    private let edo12         = EqualTemperament(divisions: 12)
    private let edo19         = EqualTemperament(divisions: 19)
    private let edo31         = EqualTemperament(divisions: 31)
    private let edo12StepSize = EqualTemperament(divisions: 12).stepSize.cents
    private let edo19StepSize = EqualTemperament(divisions: 19).stepSize.cents
    private let edo31StepSize = EqualTemperament(divisions: 31).stepSize.cents
}

// MARK: -

extension EqualTemperamentTests {
    @Test
    func realize_simple_12edo() {
        assertEqual(edo12.realize(interval: .augmented1)?.cents, edo12StepSize * 1)
        assertEqual(edo12.realize(interval: .augmented2)?.cents, edo12StepSize * 3)
        assertEqual(edo12.realize(interval: .augmented3)?.cents, edo12StepSize * 5)
        assertEqual(edo12.realize(interval: .augmented4)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .augmented5)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .augmented6)?.cents, edo12StepSize * 10)
        assertEqual(edo12.realize(interval: .augmented7)?.cents, edo12StepSize * 12)
        assertEqual(edo12.realize(interval: .diminished2)?.cents, edo12StepSize * 0)
        assertEqual(edo12.realize(interval: .diminished3)?.cents, edo12StepSize * 2)
        assertEqual(edo12.realize(interval: .diminished4)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .diminished5)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .diminished6)?.cents, edo12StepSize * 7)
        assertEqual(edo12.realize(interval: .diminished7)?.cents, edo12StepSize * 9)
        assertEqual(edo12.realize(interval: .diminished8)?.cents, edo12StepSize * 11)
        assertEqual(edo12.realize(interval: .doublyAugmented1)?.cents, edo12StepSize * 2)
        assertEqual(edo12.realize(interval: .doublyAugmented2)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .doublyAugmented3)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .doublyAugmented4)?.cents, edo12StepSize * 7)
        assertEqual(edo12.realize(interval: .doublyAugmented5)?.cents, edo12StepSize * 9)
        assertEqual(edo12.realize(interval: .doublyAugmented6)?.cents, edo12StepSize * 11)
        assertEqual(edo12.realize(interval: .doublyAugmented7)?.cents, edo12StepSize * 13)
        #expect(edo12.realize(interval: .doublyDiminished2)?.cents == nil)
        assertEqual(edo12.realize(interval: .doublyDiminished3)?.cents, edo12StepSize * 1)
        assertEqual(edo12.realize(interval: .doublyDiminished4)?.cents, edo12StepSize * 3)
        assertEqual(edo12.realize(interval: .doublyDiminished5)?.cents, edo12StepSize * 5)
        assertEqual(edo12.realize(interval: .doublyDiminished6)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .doublyDiminished7)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .doublyDiminished8)?.cents, edo12StepSize * 10)
        assertEqual(edo12.realize(interval: .major2)?.cents, edo12StepSize * 2)
        assertEqual(edo12.realize(interval: .major3)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .major6)?.cents, edo12StepSize * 9)
        assertEqual(edo12.realize(interval: .major7)?.cents, edo12StepSize * 11)
        assertEqual(edo12.realize(interval: .minor2)?.cents, edo12StepSize * 1)
        assertEqual(edo12.realize(interval: .minor3)?.cents, edo12StepSize * 3)
        assertEqual(edo12.realize(interval: .minor6)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .minor7)?.cents, edo12StepSize * 10)
        assertEqual(edo12.realize(interval: .perfect1)?.cents, edo12StepSize * 0)
        assertEqual(edo12.realize(interval: .perfect4)?.cents, edo12StepSize * 5)
        assertEqual(edo12.realize(interval: .perfect5)?.cents, edo12StepSize * 7)
        assertEqual(edo12.realize(interval: .quadruplyAugmented1)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .quadruplyAugmented2)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .quadruplyAugmented3)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .quadruplyAugmented4)?.cents, edo12StepSize * 9)
        assertEqual(edo12.realize(interval: .quadruplyAugmented5)?.cents, edo12StepSize * 11)
        assertEqual(edo12.realize(interval: .quadruplyAugmented6)?.cents, edo12StepSize * 13)
        assertEqual(edo12.realize(interval: .quadruplyAugmented7)?.cents, edo12StepSize * 15)
        #expect(edo12.realize(interval: .quadruplyDiminished2)?.cents == nil)
        #expect(edo12.realize(interval: .quadruplyDiminished3)?.cents == nil)
        assertEqual(edo12.realize(interval: .quadruplyDiminished4)?.cents, edo12StepSize * 1)
        assertEqual(edo12.realize(interval: .quadruplyDiminished5)?.cents, edo12StepSize * 3)
        assertEqual(edo12.realize(interval: .quadruplyDiminished6)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .quadruplyDiminished7)?.cents, edo12StepSize * 6)
        assertEqual(edo12.realize(interval: .quadruplyDiminished8)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .triplyAugmented1)?.cents, edo12StepSize * 3)
        assertEqual(edo12.realize(interval: .triplyAugmented2)?.cents, edo12StepSize * 5)
        assertEqual(edo12.realize(interval: .triplyAugmented3)?.cents, edo12StepSize * 7)
        assertEqual(edo12.realize(interval: .triplyAugmented4)?.cents, edo12StepSize * 8)
        assertEqual(edo12.realize(interval: .triplyAugmented5)?.cents, edo12StepSize * 10)
        assertEqual(edo12.realize(interval: .triplyAugmented6)?.cents, edo12StepSize * 12)
        assertEqual(edo12.realize(interval: .triplyAugmented7)?.cents, edo12StepSize * 14)
        #expect(edo12.realize(interval: .triplyDiminished2)?.cents == nil)
        assertEqual(edo12.realize(interval: .triplyDiminished3)?.cents, edo12StepSize * 0)
        assertEqual(edo12.realize(interval: .triplyDiminished4)?.cents, edo12StepSize * 2)
        assertEqual(edo12.realize(interval: .triplyDiminished5)?.cents, edo12StepSize * 4)
        assertEqual(edo12.realize(interval: .triplyDiminished6)?.cents, edo12StepSize * 5)
        assertEqual(edo12.realize(interval: .triplyDiminished7)?.cents, edo12StepSize * 7)
        assertEqual(edo12.realize(interval: .triplyDiminished8)?.cents, edo12StepSize * 9)
    }

    @Test
    func realize_simple_19edo() {
        assertEqual(edo19.realize(interval: .augmented1)?.cents, edo19StepSize * 1)
        assertEqual(edo19.realize(interval: .augmented2)?.cents, edo19StepSize * 4)
        assertEqual(edo19.realize(interval: .augmented3)?.cents, edo19StepSize * 7)
        assertEqual(edo19.realize(interval: .augmented4)?.cents, edo19StepSize * 9)
        assertEqual(edo19.realize(interval: .augmented5)?.cents, edo19StepSize * 12)
        assertEqual(edo19.realize(interval: .augmented6)?.cents, edo19StepSize * 15)
        assertEqual(edo19.realize(interval: .augmented7)?.cents, edo19StepSize * 18)
        assertEqual(edo19.realize(interval: .diminished2)?.cents, edo19StepSize * 1)
        assertEqual(edo19.realize(interval: .diminished3)?.cents, edo19StepSize * 4)
        assertEqual(edo19.realize(interval: .diminished4)?.cents, edo19StepSize * 7)
        assertEqual(edo19.realize(interval: .diminished5)?.cents, edo19StepSize * 10)
        assertEqual(edo19.realize(interval: .diminished6)?.cents, edo19StepSize * 12)
        assertEqual(edo19.realize(interval: .diminished7)?.cents, edo19StepSize * 15)
        assertEqual(edo19.realize(interval: .diminished8)?.cents, edo19StepSize * 18)
        assertEqual(edo19.realize(interval: .doublyAugmented1)?.cents, edo19StepSize * 2)
        assertEqual(edo19.realize(interval: .doublyAugmented2)?.cents, edo19StepSize * 5)
        assertEqual(edo19.realize(interval: .doublyAugmented3)?.cents, edo19StepSize * 8)
        assertEqual(edo19.realize(interval: .doublyAugmented4)?.cents, edo19StepSize * 10)
        assertEqual(edo19.realize(interval: .doublyAugmented5)?.cents, edo19StepSize * 13)
        assertEqual(edo19.realize(interval: .doublyAugmented6)?.cents, edo19StepSize * 16)
        assertEqual(edo19.realize(interval: .doublyAugmented7)?.cents, edo19StepSize * 19)
        assertEqual(edo19.realize(interval: .doublyDiminished2)?.cents, edo19StepSize * 0)
        assertEqual(edo19.realize(interval: .doublyDiminished3)?.cents, edo19StepSize * 3)
        assertEqual(edo19.realize(interval: .doublyDiminished4)?.cents, edo19StepSize * 6)
        assertEqual(edo19.realize(interval: .doublyDiminished5)?.cents, edo19StepSize * 9)
        assertEqual(edo19.realize(interval: .doublyDiminished6)?.cents, edo19StepSize * 11)
        assertEqual(edo19.realize(interval: .doublyDiminished7)?.cents, edo19StepSize * 14)
        assertEqual(edo19.realize(interval: .doublyDiminished8)?.cents, edo19StepSize * 17)
        assertEqual(edo19.realize(interval: .major2)?.cents, edo19StepSize * 3)
        assertEqual(edo19.realize(interval: .major3)?.cents, edo19StepSize * 6)
        assertEqual(edo19.realize(interval: .major6)?.cents, edo19StepSize * 14)
        assertEqual(edo19.realize(interval: .major7)?.cents, edo19StepSize * 17)
        assertEqual(edo19.realize(interval: .minor2)?.cents, edo19StepSize * 2)
        assertEqual(edo19.realize(interval: .minor3)?.cents, edo19StepSize * 5)
        assertEqual(edo19.realize(interval: .minor6)?.cents, edo19StepSize * 13)
        assertEqual(edo19.realize(interval: .minor7)?.cents, edo19StepSize * 16)
        assertEqual(edo19.realize(interval: .perfect1)?.cents, edo19StepSize * 0)
        assertEqual(edo19.realize(interval: .perfect4)?.cents, edo19StepSize * 8)
        assertEqual(edo19.realize(interval: .perfect5)?.cents, edo19StepSize * 11)
        assertEqual(edo19.realize(interval: .quadruplyAugmented1)?.cents, edo19StepSize * 4)
        assertEqual(edo19.realize(interval: .quadruplyAugmented2)?.cents, edo19StepSize * 7)
        assertEqual(edo19.realize(interval: .quadruplyAugmented3)?.cents, edo19StepSize * 10)
        assertEqual(edo19.realize(interval: .quadruplyAugmented4)?.cents, edo19StepSize * 12)
        assertEqual(edo19.realize(interval: .quadruplyAugmented5)?.cents, edo19StepSize * 15)
        assertEqual(edo19.realize(interval: .quadruplyAugmented6)?.cents, edo19StepSize * 18)
        assertEqual(edo19.realize(interval: .quadruplyAugmented7)?.cents, edo19StepSize * 21)
        #expect(edo19.realize(interval: .quadruplyDiminished2)?.cents == nil)
        assertEqual(edo19.realize(interval: .quadruplyDiminished3)?.cents, edo19StepSize * 1)
        assertEqual(edo19.realize(interval: .quadruplyDiminished4)?.cents, edo19StepSize * 4)
        assertEqual(edo19.realize(interval: .quadruplyDiminished5)?.cents, edo19StepSize * 7)
        assertEqual(edo19.realize(interval: .quadruplyDiminished6)?.cents, edo19StepSize * 9)
        assertEqual(edo19.realize(interval: .quadruplyDiminished7)?.cents, edo19StepSize * 12)
        assertEqual(edo19.realize(interval: .quadruplyDiminished8)?.cents, edo19StepSize * 15)
        assertEqual(edo19.realize(interval: .triplyAugmented1)?.cents, edo19StepSize * 3)
        assertEqual(edo19.realize(interval: .triplyAugmented2)?.cents, edo19StepSize * 6)
        assertEqual(edo19.realize(interval: .triplyAugmented3)?.cents, edo19StepSize * 9)
        assertEqual(edo19.realize(interval: .triplyAugmented4)?.cents, edo19StepSize * 11)
        assertEqual(edo19.realize(interval: .triplyAugmented5)?.cents, edo19StepSize * 14)
        assertEqual(edo19.realize(interval: .triplyAugmented6)?.cents, edo19StepSize * 17)
        assertEqual(edo19.realize(interval: .triplyAugmented7)?.cents, edo19StepSize * 20)
        #expect(edo19.realize(interval: .triplyDiminished2)?.cents == nil)
        assertEqual(edo19.realize(interval: .triplyDiminished3)?.cents, edo19StepSize * 2)
        assertEqual(edo19.realize(interval: .triplyDiminished4)?.cents, edo19StepSize * 5)
        assertEqual(edo19.realize(interval: .triplyDiminished5)?.cents, edo19StepSize * 8)
        assertEqual(edo19.realize(interval: .triplyDiminished6)?.cents, edo19StepSize * 10)
        assertEqual(edo19.realize(interval: .triplyDiminished7)?.cents, edo19StepSize * 13)
        assertEqual(edo19.realize(interval: .triplyDiminished8)?.cents, edo19StepSize * 16)
    }

    @Test
    func realize_simple_31edo() {
        assertEqual(edo31.realize(interval: .augmented1)?.cents, edo31StepSize * 2)
        assertEqual(edo31.realize(interval: .augmented2)?.cents, edo31StepSize * 7)
        assertEqual(edo31.realize(interval: .augmented3)?.cents, edo31StepSize * 12)
        assertEqual(edo31.realize(interval: .augmented4)?.cents, edo31StepSize * 15)
        assertEqual(edo31.realize(interval: .augmented5)?.cents, edo31StepSize * 20)
        assertEqual(edo31.realize(interval: .augmented6)?.cents, edo31StepSize * 25)
        assertEqual(edo31.realize(interval: .augmented7)?.cents, edo31StepSize * 30)
        assertEqual(edo31.realize(interval: .diminished2)?.cents, edo31StepSize * 1)
        assertEqual(edo31.realize(interval: .diminished3)?.cents, edo31StepSize * 6)
        assertEqual(edo31.realize(interval: .diminished4)?.cents, edo31StepSize * 11)
        assertEqual(edo31.realize(interval: .diminished5)?.cents, edo31StepSize * 16)
        assertEqual(edo31.realize(interval: .diminished6)?.cents, edo31StepSize * 19)
        assertEqual(edo31.realize(interval: .diminished7)?.cents, edo31StepSize * 24)
        assertEqual(edo31.realize(interval: .diminished8)?.cents, edo31StepSize * 29)
        assertEqual(edo31.realize(interval: .doublyAugmented1)?.cents, edo31StepSize * 4)
        assertEqual(edo31.realize(interval: .doublyAugmented2)?.cents, edo31StepSize * 9)
        assertEqual(edo31.realize(interval: .doublyAugmented3)?.cents, edo31StepSize * 14)
        assertEqual(edo31.realize(interval: .doublyAugmented4)?.cents, edo31StepSize * 17)
        assertEqual(edo31.realize(interval: .doublyAugmented5)?.cents, edo31StepSize * 22)
        assertEqual(edo31.realize(interval: .doublyAugmented6)?.cents, edo31StepSize * 27)
        assertEqual(edo31.realize(interval: .doublyAugmented7)?.cents, edo31StepSize * 32)
        #expect(edo31.realize(interval: .doublyDiminished2)?.cents == nil)
        assertEqual(edo31.realize(interval: .doublyDiminished3)?.cents, edo31StepSize * 4)
        assertEqual(edo31.realize(interval: .doublyDiminished4)?.cents, edo31StepSize * 9)
        assertEqual(edo31.realize(interval: .doublyDiminished5)?.cents, edo31StepSize * 14)
        assertEqual(edo31.realize(interval: .doublyDiminished6)?.cents, edo31StepSize * 17)
        assertEqual(edo31.realize(interval: .doublyDiminished7)?.cents, edo31StepSize * 22)
        assertEqual(edo31.realize(interval: .doublyDiminished8)?.cents, edo31StepSize * 27)
        assertEqual(edo31.realize(interval: .major2)?.cents, edo31StepSize * 5)
        assertEqual(edo31.realize(interval: .major3)?.cents, edo31StepSize * 10)
        assertEqual(edo31.realize(interval: .major6)?.cents, edo31StepSize * 23)
        assertEqual(edo31.realize(interval: .major7)?.cents, edo31StepSize * 28)
        assertEqual(edo31.realize(interval: .minor2)?.cents, edo31StepSize * 3)
        assertEqual(edo31.realize(interval: .minor3)?.cents, edo31StepSize * 8)
        assertEqual(edo31.realize(interval: .minor6)?.cents, edo31StepSize * 21)
        assertEqual(edo31.realize(interval: .minor7)?.cents, edo31StepSize * 26)
        assertEqual(edo31.realize(interval: .perfect1)?.cents, edo31StepSize * 0)
        assertEqual(edo31.realize(interval: .perfect4)?.cents, edo31StepSize * 13)
        assertEqual(edo31.realize(interval: .perfect5)?.cents, edo31StepSize * 18)
        assertEqual(edo31.realize(interval: .quadruplyAugmented1)?.cents, edo31StepSize * 8)
        assertEqual(edo31.realize(interval: .quadruplyAugmented2)?.cents, edo31StepSize * 13)
        assertEqual(edo31.realize(interval: .quadruplyAugmented3)?.cents, edo31StepSize * 18)
        assertEqual(edo31.realize(interval: .quadruplyAugmented4)?.cents, edo31StepSize * 21)
        assertEqual(edo31.realize(interval: .quadruplyAugmented5)?.cents, edo31StepSize * 26)
        assertEqual(edo31.realize(interval: .quadruplyAugmented6)?.cents, edo31StepSize * 31)
        assertEqual(edo31.realize(interval: .quadruplyAugmented7)?.cents, edo31StepSize * 36)
        #expect(edo31.realize(interval: .quadruplyDiminished2)?.cents == nil)
        assertEqual(edo31.realize(interval: .quadruplyDiminished3)?.cents, edo31StepSize * 0)
        assertEqual(edo31.realize(interval: .quadruplyDiminished4)?.cents, edo31StepSize * 5)
        assertEqual(edo31.realize(interval: .quadruplyDiminished5)?.cents, edo31StepSize * 10)
        assertEqual(edo31.realize(interval: .quadruplyDiminished6)?.cents, edo31StepSize * 13)
        assertEqual(edo31.realize(interval: .quadruplyDiminished7)?.cents, edo31StepSize * 18)
        assertEqual(edo31.realize(interval: .quadruplyDiminished8)?.cents, edo31StepSize * 23)
        assertEqual(edo31.realize(interval: .triplyAugmented1)?.cents, edo31StepSize * 6)
        assertEqual(edo31.realize(interval: .triplyAugmented2)?.cents, edo31StepSize * 11)
        assertEqual(edo31.realize(interval: .triplyAugmented3)?.cents, edo31StepSize * 16)
        assertEqual(edo31.realize(interval: .triplyAugmented4)?.cents, edo31StepSize * 19)
        assertEqual(edo31.realize(interval: .triplyAugmented5)?.cents, edo31StepSize * 24)
        assertEqual(edo31.realize(interval: .triplyAugmented6)?.cents, edo31StepSize * 29)
        assertEqual(edo31.realize(interval: .triplyAugmented7)?.cents, edo31StepSize * 34)
        #expect(edo31.realize(interval: .triplyDiminished2)?.cents == nil)
        assertEqual(edo31.realize(interval: .triplyDiminished3)?.cents, edo31StepSize * 2)
        assertEqual(edo31.realize(interval: .triplyDiminished4)?.cents, edo31StepSize * 7)
        assertEqual(edo31.realize(interval: .triplyDiminished5)?.cents, edo31StepSize * 12)
        assertEqual(edo31.realize(interval: .triplyDiminished6)?.cents, edo31StepSize * 15)
        assertEqual(edo31.realize(interval: .triplyDiminished7)?.cents, edo31StepSize * 20)
        assertEqual(edo31.realize(interval: .triplyDiminished8)?.cents, edo31StepSize * 25)
    }
}
