private import XestiTools

extension Interval {
    public static let perfect1              = Interval(.perfect, 1)
    public static let augmented1            = Interval(.augmented, 1)
    public static let doublyAugmented1      = Interval(.doublyAugmented, 1)
    public static let triplyAugmented1      = Interval(.triplyAugmented, 1)
    public static let quadruplyAugmented1   = Interval(.quadruplyAugmented, 1)

    public static let quadruplyDiminished2  = Interval(.quadruplyDiminished, 2)
    public static let triplyDiminished2     = Interval(.triplyDiminished, 2)
    public static let doublyDiminished2     = Interval(.doublyDiminished, 2)
    public static let diminished2           = Interval(.diminished, 2)
    public static let minor2                = Interval(.minor, 2)
    public static let major2                = Interval(.major, 2)
    public static let augmented2            = Interval(.augmented, 2)
    public static let doublyAugmented2      = Interval(.doublyAugmented, 2)
    public static let triplyAugmented2      = Interval(.triplyAugmented, 2)
    public static let quadruplyAugmented2   = Interval(.quadruplyAugmented, 2)

    public static let quadruplyDiminished3  = Interval(.quadruplyDiminished, 3)
    public static let triplyDiminished3     = Interval(.triplyDiminished, 3)
    public static let doublyDiminished3     = Interval(.doublyDiminished, 3)
    public static let diminished3           = Interval(.diminished, 3)
    public static let minor3                = Interval(.minor, 3)
    public static let major3                = Interval(.major, 3)
    public static let augmented3            = Interval(.augmented, 3)
    public static let doublyAugmented3      = Interval(.doublyAugmented, 3)
    public static let triplyAugmented3      = Interval(.triplyAugmented, 3)
    public static let quadruplyAugmented3   = Interval(.quadruplyAugmented, 3)

    public static let quadruplyDiminished4  = Interval(.quadruplyDiminished, 4)
    public static let triplyDiminished4     = Interval(.triplyDiminished, 4)
    public static let doublyDiminished4     = Interval(.doublyDiminished, 4)
    public static let diminished4           = Interval(.diminished, 4)
    public static let perfect4              = Interval(.perfect, 4)
    public static let augmented4            = Interval(.augmented, 4)
    public static let doublyAugmented4      = Interval(.doublyAugmented, 4)
    public static let triplyAugmented4      = Interval(.triplyAugmented, 4)
    public static let quadruplyAugmented4   = Interval(.quadruplyAugmented, 4)

    public static let quadruplyDiminished5  = Interval(.quadruplyDiminished, 5)
    public static let triplyDiminished5     = Interval(.triplyDiminished, 5)
    public static let doublyDiminished5     = Interval(.doublyDiminished, 5)
    public static let diminished5           = Interval(.diminished, 5)
    public static let perfect5              = Interval(.perfect, 5)
    public static let augmented5            = Interval(.augmented, 5)
    public static let doublyAugmented5      = Interval(.doublyAugmented, 5)
    public static let triplyAugmented5      = Interval(.triplyAugmented, 5)
    public static let quadruplyAugmented5   = Interval(.quadruplyAugmented, 5)

    public static let quadruplyDiminished6  = Interval(.quadruplyDiminished, 6)
    public static let triplyDiminished6     = Interval(.triplyDiminished, 6)
    public static let doublyDiminished6     = Interval(.doublyDiminished, 6)
    public static let diminished6           = Interval(.diminished, 6)
    public static let minor6                = Interval(.minor, 6)
    public static let major6                = Interval(.major, 6)
    public static let augmented6            = Interval(.augmented, 6)
    public static let doublyAugmented6      = Interval(.doublyAugmented, 6)
    public static let triplyAugmented6      = Interval(.triplyAugmented, 6)
    public static let quadruplyAugmented6   = Interval(.quadruplyAugmented, 6)

    public static let quadruplyDiminished7  = Interval(.quadruplyDiminished, 7)
    public static let triplyDiminished7     = Interval(.triplyDiminished, 7)
    public static let doublyDiminished7     = Interval(.doublyDiminished, 7)
    public static let diminished7           = Interval(.diminished, 7)
    public static let minor7                = Interval(.minor, 7)
    public static let major7                = Interval(.major, 7)
    public static let augmented7            = Interval(.augmented, 7)
    public static let doublyAugmented7      = Interval(.doublyAugmented, 7)
    public static let triplyAugmented7      = Interval(.triplyAugmented, 7)
    public static let quadruplyAugmented7   = Interval(.quadruplyAugmented, 7)

    public static let quadruplyDiminished8  = Interval(.quadruplyDiminished, 8)
    public static let triplyDiminished8     = Interval(.triplyDiminished, 8)
    public static let doublyDiminished8     = Interval(.doublyDiminished, 8)
    public static let diminished8           = Interval(.diminished, 8)
    public static let perfect8              = Interval(.perfect, 8)
    public static let augmented8            = Interval(.augmented, 8)
    public static let doublyAugmented8      = Interval(.doublyAugmented, 8)
    public static let triplyAugmented8      = Interval(.triplyAugmented, 8)
    public static let quadruplyAugmented8   = Interval(.quadruplyAugmented, 8)

    public static let quadruplyDiminished9  = Interval(.quadruplyDiminished, 9)
    public static let triplyDiminished9     = Interval(.triplyDiminished, 9)
    public static let doublyDiminished9     = Interval(.doublyDiminished, 9)
    public static let diminished9           = Interval(.diminished, 9)
    public static let minor9                = Interval(.minor, 9)
    public static let major9                = Interval(.major, 9)
    public static let augmented9            = Interval(.augmented, 9)
    public static let doublyAugmented9      = Interval(.doublyAugmented, 9)
    public static let triplyAugmented9      = Interval(.triplyAugmented, 9)
    public static let quadruplyAugmented9   = Interval(.quadruplyAugmented, 9)

    public static let quadruplyDiminished10 = Interval(.quadruplyDiminished, 10)
    public static let triplyDiminished10    = Interval(.triplyDiminished, 10)
    public static let doublyDiminished10    = Interval(.doublyDiminished, 10)
    public static let diminished10          = Interval(.diminished, 10)
    public static let minor10               = Interval(.minor, 10)
    public static let major10               = Interval(.major, 10)
    public static let augmented10           = Interval(.augmented, 10)
    public static let doublyAugmented10     = Interval(.doublyAugmented, 10)
    public static let triplyAugmented10     = Interval(.triplyAugmented, 10)
    public static let quadruplyAugmented10  = Interval(.quadruplyAugmented, 10)

    public static let quadruplyDiminished11 = Interval(.quadruplyDiminished, 11)
    public static let triplyDiminished11    = Interval(.triplyDiminished, 11)
    public static let doublyDiminished11    = Interval(.doublyDiminished, 11)
    public static let diminished11          = Interval(.diminished, 11)
    public static let perfect11             = Interval(.perfect, 11)
    public static let augmented11           = Interval(.augmented, 11)
    public static let doublyAugmented11     = Interval(.doublyAugmented, 11)
    public static let triplyAugmented11     = Interval(.triplyAugmented, 11)
    public static let quadruplyAugmented11  = Interval(.quadruplyAugmented, 11)

    public static let quadruplyDiminished12 = Interval(.quadruplyDiminished, 12)
    public static let triplyDiminished12    = Interval(.triplyDiminished, 12)
    public static let doublyDiminished12    = Interval(.doublyDiminished, 12)
    public static let diminished12          = Interval(.diminished, 12)
    public static let perfect12             = Interval(.perfect, 12)
    public static let augmented12           = Interval(.augmented, 12)
    public static let doublyAugmented12     = Interval(.doublyAugmented, 12)
    public static let triplyAugmented12     = Interval(.triplyAugmented, 12)
    public static let quadruplyAugmented12  = Interval(.quadruplyAugmented, 12)

    public static let quadruplyDiminished13 = Interval(.quadruplyDiminished, 13)
    public static let triplyDiminished13    = Interval(.triplyDiminished, 13)
    public static let doublyDiminished13    = Interval(.doublyDiminished, 13)
    public static let diminished13          = Interval(.diminished, 13)
    public static let minor13               = Interval(.minor, 13)
    public static let major13               = Interval(.major, 13)
    public static let augmented13           = Interval(.augmented, 13)
    public static let doublyAugmented13     = Interval(.doublyAugmented, 13)
    public static let triplyAugmented13     = Interval(.triplyAugmented, 13)
    public static let quadruplyAugmented13  = Interval(.quadruplyAugmented, 13)

    public static let quadruplyDiminished14 = Interval(.quadruplyDiminished, 14)
    public static let triplyDiminished14    = Interval(.triplyDiminished, 14)
    public static let doublyDiminished14    = Interval(.doublyDiminished, 14)
    public static let diminished14          = Interval(.diminished, 14)
    public static let minor14               = Interval(.minor, 14)
    public static let major14               = Interval(.major, 14)
    public static let augmented14           = Interval(.augmented, 14)
    public static let doublyAugmented14     = Interval(.doublyAugmented, 14)
    public static let triplyAugmented14     = Interval(.triplyAugmented, 14)
    public static let quadruplyAugmented14  = Interval(.quadruplyAugmented, 14)

    public static let quadruplyDiminished15 = Interval(.quadruplyDiminished, 15)
    public static let triplyDiminished15    = Interval(.triplyDiminished, 15)
    public static let doublyDiminished15    = Interval(.doublyDiminished, 15)
    public static let diminished15          = Interval(.diminished, 15)
    public static let perfect15             = Interval(.perfect, 15)
    public static let augmented15           = Interval(.augmented, 15)
    public static let doublyAugmented15     = Interval(.doublyAugmented, 15)
    public static let triplyAugmented15     = Interval(.triplyAugmented, 15)
    public static let quadruplyAugmented15  = Interval(.quadruplyAugmented, 15)
}
