// © 2025–2026 John Gary Pusey (see LICENSE.md)

@testable import IvorTuning
import Testing

// swiftlint:disable file_length

struct FrequencyTests {
}

// MARK: -

extension FrequencyTests {
    @Test
    func intervalFailure() {
    }

    @Test
    func intervalSuccess1() {
        assertEqual(Fixtures.c4.interval(to: Fixtures.c4), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cSharp4), (Fixtures.augmented1, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dDoubleFlat4), (Fixtures.diminished2, .same))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dFlat4), (Fixtures.minor2, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.d4), (Fixtures.major2, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dSharp4), (Fixtures.augmented2, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eDoubleFlat4), (Fixtures.diminished3, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eFlat4), (Fixtures.minor3, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.e4), (Fixtures.major3, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eSharp4), (Fixtures.augmented3, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fDoubleFlat4), (Fixtures.doublyDiminished4, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fFlat4), (Fixtures.diminished4, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.f4), (Fixtures.perfect4, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fSharp4), (Fixtures.augmented4, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gFlat4), (Fixtures.diminished5, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.g4), (Fixtures.perfect5, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gSharp4), (Fixtures.augmented5, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aDoubleFlat4), (Fixtures.diminished6, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aFlat4), (Fixtures.minor6, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.a4), (Fixtures.major6, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aSharp4), (Fixtures.augmented6, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bDoubleFlat4), (Fixtures.diminished7, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bFlat4), (Fixtures.minor7, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.b4), (Fixtures.major7, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bSharp4), (Fixtures.augmented7, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cDoubleFlat5), (Fixtures.doublyDiminished8, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cFlat5), (Fixtures.diminished8, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.c5), (Fixtures.perfect8, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cSharp5), (Fixtures.augmented8, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dDoubleFlat5), (Fixtures.diminished9, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dFlat5), (Fixtures.minor9, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.d5), (Fixtures.major9, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dSharp5), (Fixtures.augmented9, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eDoubleFlat5), (Fixtures.diminished10, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eFlat5), (Fixtures.minor10, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.e5), (Fixtures.major10, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eSharp5), (Fixtures.augmented10, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fDoubleFlat5), (Fixtures.doublyDiminished11, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fFlat5), (Fixtures.diminished11, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.f5), (Fixtures.perfect11, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fSharp5), (Fixtures.augmented11, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gFlat5), (Fixtures.diminished12, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.g5), (Fixtures.perfect12, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gSharp5), (Fixtures.augmented12, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aDoubleFlat5), (Fixtures.diminished13, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aFlat5), (Fixtures.minor13, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.a5), (Fixtures.major13, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aSharp5), (Fixtures.augmented13, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bDoubleFlat5), (Fixtures.diminished14, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bFlat5), (Fixtures.minor14, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.b5), (Fixtures.major14, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bSharp5), (Fixtures.augmented14, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cDoubleFlat6), (Fixtures.doublyDiminished15, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cFlat6), (Fixtures.diminished15, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.c6), (Fixtures.perfect15, .ascending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cSharp6), (Fixtures.augmented15, .ascending))

        assertEqual(Fixtures.cDoubleFlat4.interval(to: Fixtures.cDoubleSharp4), (Fixtures.quadruplyAugmented1, .ascending))
    }

    @Test
    func intervalSuccess2() {
        assertEqual(Fixtures.e6.interval(to: Fixtures.e6), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eSharp6), (Fixtures.augmented1, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fFlat6), (Fixtures.diminished2, .same))
        assertEqual(Fixtures.e6.interval(to: Fixtures.f6), (Fixtures.minor2, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fSharp6), (Fixtures.major2, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fDoubleSharp6), (Fixtures.augmented2, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gFlat6), (Fixtures.diminished3, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.g6), (Fixtures.minor3, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gSharp6), (Fixtures.major3, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gDoubleSharp6), (Fixtures.augmented3, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aFlat6), (Fixtures.diminished4, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.a6), (Fixtures.perfect4, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aSharp6), (Fixtures.augmented4, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bFlat6), (Fixtures.diminished5, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.b6), (Fixtures.perfect5, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bSharp6), (Fixtures.augmented5, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cFlat7), (Fixtures.diminished6, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.c7), (Fixtures.minor6, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cSharp7), (Fixtures.major6, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cDoubleSharp7), (Fixtures.augmented6, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dFlat7), (Fixtures.diminished7, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.d7), (Fixtures.minor7, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dSharp7), (Fixtures.major7, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dDoubleSharp7), (Fixtures.augmented7, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eFlat7), (Fixtures.diminished8, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.e7), (Fixtures.perfect8, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eSharp7), (Fixtures.augmented8, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fFlat7), (Fixtures.diminished9, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.f7), (Fixtures.minor9, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fSharp7), (Fixtures.major9, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fDoubleSharp7), (Fixtures.augmented9, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gFlat7), (Fixtures.diminished10, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.g7), (Fixtures.minor10, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gSharp7), (Fixtures.major10, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gDoubleSharp7), (Fixtures.augmented10, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aFlat7), (Fixtures.diminished11, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.a7), (Fixtures.perfect11, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aSharp7), (Fixtures.augmented11, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bFlat7), (Fixtures.diminished12, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.b7), (Fixtures.perfect12, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bSharp7), (Fixtures.augmented12, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cFlat8), (Fixtures.diminished13, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.c8), (Fixtures.minor13, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cSharp8), (Fixtures.major13, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cDoubleSharp8), (Fixtures.augmented13, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dFlat8), (Fixtures.diminished14, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.d8), (Fixtures.minor14, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dSharp8), (Fixtures.major14, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dDoubleSharp8), (Fixtures.augmented14, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eFlat8), (Fixtures.diminished15, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.e8), (Fixtures.perfect15, .ascending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eSharp8), (Fixtures.augmented15, .ascending))
    }

    @Test
    func intervalSuccess3() {
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat2), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.a2), (Fixtures.augmented1, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bDoubleFlat2), (Fixtures.minor2, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bFlat2), (Fixtures.major2, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.b2), (Fixtures.augmented2, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cDoubleFlat3), (Fixtures.diminished3, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cFlat3), (Fixtures.minor3, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.c3), (Fixtures.major3, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cSharp3), (Fixtures.augmented3, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dDoubleFlat3), (Fixtures.diminished4, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dFlat3), (Fixtures.perfect4, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.d3), (Fixtures.augmented4, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eDoubleFlat3), (Fixtures.diminished5, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eFlat3), (Fixtures.perfect5, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.e3), (Fixtures.augmented5, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fDoubleFlat3), (Fixtures.diminished6, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fFlat3), (Fixtures.minor6, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.f3), (Fixtures.major6, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fSharp3), (Fixtures.augmented6, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gDoubleFlat3), (Fixtures.diminished7, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gFlat3), (Fixtures.minor7, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.g3), (Fixtures.major7, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gSharp3), (Fixtures.augmented7, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aDoubleFlat3), (Fixtures.diminished8, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat3), (Fixtures.perfect8, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.a3), (Fixtures.augmented8, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bDoubleFlat3), (Fixtures.minor9, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bFlat3), (Fixtures.major9, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.b3), (Fixtures.augmented9, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cDoubleFlat4), (Fixtures.diminished10, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cFlat4), (Fixtures.minor10, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.c4), (Fixtures.major10, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cSharp4), (Fixtures.augmented10, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dDoubleFlat4), (Fixtures.diminished11, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dFlat4), (Fixtures.perfect11, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.d4), (Fixtures.augmented11, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eDoubleFlat4), (Fixtures.diminished12, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eFlat4), (Fixtures.perfect12, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.e4), (Fixtures.augmented12, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fDoubleFlat4), (Fixtures.diminished13, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fFlat4), (Fixtures.minor13, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.f4), (Fixtures.major13, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fSharp4), (Fixtures.augmented13, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gDoubleFlat4), (Fixtures.diminished14, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gFlat4), (Fixtures.minor14, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.g4), (Fixtures.major14, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gSharp4), (Fixtures.augmented14, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aDoubleFlat4), (Fixtures.diminished15, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat4), (Fixtures.perfect15, .ascending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.a4), (Fixtures.augmented15, .ascending))
    }

    @Test
    func intervalSuccess4() {
        assertEqual(Fixtures.c4.interval(to: Fixtures.c4), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cFlat4), (Fixtures.augmented1, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cDoubleFlat4), (Fixtures.doublyAugmented1, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bSharp3), (Fixtures.diminished2, .same))
        assertEqual(Fixtures.c4.interval(to: Fixtures.b3), (Fixtures.minor2, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bFlat3), (Fixtures.major2, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bDoubleFlat3), (Fixtures.augmented2, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aSharp3), (Fixtures.diminished3, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.a3), (Fixtures.minor3, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aFlat3), (Fixtures.major3, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aDoubleFlat3), (Fixtures.augmented3, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gSharp3), (Fixtures.diminished4, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.g3), (Fixtures.perfect4, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gFlat3), (Fixtures.augmented4, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fSharp3), (Fixtures.diminished5, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.f3), (Fixtures.perfect5, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fFlat3), (Fixtures.augmented5, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eSharp3), (Fixtures.diminished6, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.e3), (Fixtures.minor6, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eFlat3), (Fixtures.major6, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eDoubleFlat3), (Fixtures.augmented6, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dSharp3), (Fixtures.diminished7, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.d3), (Fixtures.minor7, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dFlat3), (Fixtures.major7, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dDoubleFlat3), (Fixtures.augmented7, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cSharp3), (Fixtures.diminished8, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.c3), (Fixtures.perfect8, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cFlat3), (Fixtures.augmented8, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bSharp2), (Fixtures.diminished9, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.b2), (Fixtures.minor9, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bFlat2), (Fixtures.major9, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.bDoubleFlat2), (Fixtures.augmented9, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aSharp2), (Fixtures.diminished10, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.a2), (Fixtures.minor10, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aFlat2), (Fixtures.major10, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.aDoubleFlat2), (Fixtures.augmented10, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gSharp2), (Fixtures.diminished11, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.g2), (Fixtures.perfect11, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.gFlat2), (Fixtures.augmented11, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fSharp2), (Fixtures.diminished12, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.f2), (Fixtures.perfect12, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.fFlat2), (Fixtures.augmented12, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eSharp2), (Fixtures.diminished13, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.e2), (Fixtures.minor13, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eFlat2), (Fixtures.major13, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.eDoubleFlat2), (Fixtures.augmented13, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dSharp2), (Fixtures.diminished14, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.d2), (Fixtures.minor14, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dFlat2), (Fixtures.major14, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.dDoubleFlat2), (Fixtures.augmented14, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cSharp2), (Fixtures.diminished15, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.c2), (Fixtures.perfect15, .descending))
        assertEqual(Fixtures.c4.interval(to: Fixtures.cFlat2), (Fixtures.augmented15, .descending))
    }

    @Test
    func intervalSuccess5() {
        assertEqual(Fixtures.e6.interval(to: Fixtures.e6), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eFlat6), (Fixtures.augmented1, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dDoubleSharp6), (Fixtures.diminished2, .same))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dSharp6), (Fixtures.minor2, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.d6), (Fixtures.major2, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dFlat6), (Fixtures.augmented2, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cDoubleSharp6), (Fixtures.diminished3, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cSharp6), (Fixtures.minor3, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.c6), (Fixtures.major3, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cFlat6), (Fixtures.augmented3, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bSharp5), (Fixtures.diminished4, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.b5), (Fixtures.perfect4, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bFlat5), (Fixtures.augmented4, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aSharp5), (Fixtures.diminished5, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.a5), (Fixtures.perfect5, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aFlat5), (Fixtures.augmented5, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gDoubleSharp5), (Fixtures.diminished6, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gSharp5), (Fixtures.minor6, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.g5), (Fixtures.major6, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gFlat5), (Fixtures.augmented6, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fDoubleSharp5), (Fixtures.diminished7, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fSharp5), (Fixtures.minor7, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.f5), (Fixtures.major7, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fFlat5), (Fixtures.augmented7, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eSharp5), (Fixtures.diminished8, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.e5), (Fixtures.perfect8, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eFlat5), (Fixtures.augmented8, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dDoubleSharp5), (Fixtures.diminished9, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dSharp5), (Fixtures.minor9, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.d5), (Fixtures.major9, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.dFlat5), (Fixtures.augmented9, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cDoubleSharp5), (Fixtures.diminished10, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cSharp5), (Fixtures.minor10, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.c5), (Fixtures.major10, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.cFlat5), (Fixtures.augmented10, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bSharp4), (Fixtures.diminished11, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.b4), (Fixtures.perfect11, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.bFlat4), (Fixtures.augmented11, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aSharp4), (Fixtures.diminished12, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.a4), (Fixtures.perfect12, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.aFlat4), (Fixtures.augmented12, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gDoubleSharp4), (Fixtures.diminished13, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gSharp4), (Fixtures.minor13, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.g4), (Fixtures.major13, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.gFlat4), (Fixtures.augmented13, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fDoubleSharp4), (Fixtures.diminished14, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fSharp4), (Fixtures.minor14, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.f4), (Fixtures.major14, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.fFlat4), (Fixtures.augmented14, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eSharp4), (Fixtures.diminished15, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.e4), (Fixtures.perfect15, .descending))
        assertEqual(Fixtures.e6.interval(to: Fixtures.eFlat4), (Fixtures.augmented15, .descending))
    }

    @Test
    func intervalSuccess6() {
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat2), (Fixtures.perfect1, .same))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aDoubleFlat2), (Fixtures.augmented1, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gSharp2), (Fixtures.diminished2, .same))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.g2), (Fixtures.minor2, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gFlat2), (Fixtures.major2, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gDoubleFlat2), (Fixtures.augmented2, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fSharp2), (Fixtures.diminished3, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.f2), (Fixtures.minor3, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fFlat2), (Fixtures.major3, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fDoubleFlat2), (Fixtures.augmented3, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.e2), (Fixtures.diminished4, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eFlat2), (Fixtures.perfect4, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eDoubleFlat2), (Fixtures.augmented4, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.d2), (Fixtures.diminished5, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dFlat2), (Fixtures.perfect5, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dDoubleFlat2), (Fixtures.augmented5, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cSharp2), (Fixtures.diminished6, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.c2), (Fixtures.minor6, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cFlat2), (Fixtures.major6, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cDoubleFlat2), (Fixtures.augmented6, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.b1), (Fixtures.diminished7, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bFlat1), (Fixtures.minor7, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bDoubleFlat1), (Fixtures.major7, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.a1), (Fixtures.diminished8, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat1), (Fixtures.perfect8, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aDoubleFlat1), (Fixtures.augmented8, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gSharp1), (Fixtures.diminished9, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.g1), (Fixtures.minor9, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gFlat1), (Fixtures.major9, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.gDoubleFlat1), (Fixtures.augmented9, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fSharp1), (Fixtures.diminished10, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.f1), (Fixtures.minor10, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fFlat1), (Fixtures.major10, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.fDoubleFlat1), (Fixtures.augmented10, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.e1), (Fixtures.diminished11, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eFlat1), (Fixtures.perfect11, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.eDoubleFlat1), (Fixtures.augmented11, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.d1), (Fixtures.diminished12, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dFlat1), (Fixtures.perfect12, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.dDoubleFlat1), (Fixtures.augmented12, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cSharp1), (Fixtures.diminished13, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.c1), (Fixtures.minor13, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cFlat1), (Fixtures.major13, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.cDoubleFlat1), (Fixtures.augmented13, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.b0), (Fixtures.diminished14, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bFlat0), (Fixtures.minor14, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.bDoubleFlat0), (Fixtures.major14, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.a0), (Fixtures.diminished15, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aFlat0), (Fixtures.perfect15, .descending))
        assertEqual(Fixtures.aFlat2.interval(to: Fixtures.aDoubleFlat0), (Fixtures.augmented15, .descending))
    }

    @Test
    func transposeAscFailure() {
    }

    @Test
    func transposeAscSuccess1() {
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.c4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .ascending)), Fixtures.cSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished2, direction: .same)), Fixtures.dDoubleFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .ascending)), Fixtures.dFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .ascending)), Fixtures.d4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .ascending)), Fixtures.dSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .ascending)), Fixtures.eDoubleFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .ascending)), Fixtures.eFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .ascending)), Fixtures.e4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .ascending)), Fixtures.eSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .ascending)), Fixtures.fFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .ascending)), Fixtures.f4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .ascending)), Fixtures.fSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .ascending)), Fixtures.gFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .ascending)), Fixtures.g4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .ascending)), Fixtures.gSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .ascending)), Fixtures.aDoubleFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .ascending)), Fixtures.aFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .ascending)), Fixtures.a4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .ascending)), Fixtures.aSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .ascending)), Fixtures.bDoubleFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .ascending)), Fixtures.bFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .ascending)), Fixtures.b4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented7, direction: .ascending)), Fixtures.bSharp4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .ascending)), Fixtures.cFlat5)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .ascending)), Fixtures.c5)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .ascending)), Fixtures.cSharp5)
    }

    @Test
    func transposeAscSuccess2() {
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.e6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .ascending)), Fixtures.eSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished2, direction: .same)), Fixtures.fFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .ascending)), Fixtures.f6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .ascending)), Fixtures.fSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .ascending)), Fixtures.fDoubleSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .ascending)), Fixtures.gFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .ascending)), Fixtures.g6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .ascending)), Fixtures.gSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .ascending)), Fixtures.gDoubleSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .ascending)), Fixtures.aFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .ascending)), Fixtures.a6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .ascending)), Fixtures.aSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .ascending)), Fixtures.bFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .ascending)), Fixtures.b6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .ascending)), Fixtures.bSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .ascending)), Fixtures.cFlat7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .ascending)), Fixtures.c7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .ascending)), Fixtures.cSharp7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .ascending)), Fixtures.cDoubleSharp7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .ascending)), Fixtures.dFlat7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .ascending)), Fixtures.d7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .ascending)), Fixtures.dSharp7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented7, direction: .ascending)), Fixtures.dDoubleSharp7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .ascending)), Fixtures.eFlat7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .ascending)), Fixtures.e7)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .ascending)), Fixtures.eSharp7)
    }

    @Test
    func transposeAscSuccess3() {
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.aFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .ascending)), Fixtures.a2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .ascending)), Fixtures.bDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .ascending)), Fixtures.bFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .ascending)), Fixtures.b2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .ascending)), Fixtures.cDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .ascending)), Fixtures.cFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .ascending)), Fixtures.c3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .ascending)), Fixtures.cSharp3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .ascending)), Fixtures.dDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .ascending)), Fixtures.dFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .ascending)), Fixtures.d3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .ascending)), Fixtures.eDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .ascending)), Fixtures.eFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .ascending)), Fixtures.e3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .ascending)), Fixtures.fDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .ascending)), Fixtures.fFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .ascending)), Fixtures.f3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .ascending)), Fixtures.fSharp3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .ascending)), Fixtures.gDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .ascending)), Fixtures.gFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .ascending)), Fixtures.g3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented7, direction: .ascending)), Fixtures.gSharp3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .ascending)), Fixtures.aDoubleFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .ascending)), Fixtures.aFlat3)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .ascending)), Fixtures.a3)
    }

    @Test
    func transposeDescFailure() {
    }

    @Test
    func transposeDescSuccess1() {
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.c4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .descending)), Fixtures.cFlat4)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished2, direction: .same)), Fixtures.bSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .descending)), Fixtures.b3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .descending)), Fixtures.bFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .descending)), Fixtures.bDoubleFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .descending)), Fixtures.aSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .descending)), Fixtures.a3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .descending)), Fixtures.aFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .descending)), Fixtures.aDoubleFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .descending)), Fixtures.gSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .descending)), Fixtures.g3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .descending)), Fixtures.gFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .descending)), Fixtures.fSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .descending)), Fixtures.f3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .descending)), Fixtures.fFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .descending)), Fixtures.eSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .descending)), Fixtures.e3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .descending)), Fixtures.eFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .descending)), Fixtures.eDoubleFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .descending)), Fixtures.dSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .descending)), Fixtures.d3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .descending)), Fixtures.dFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented7, direction: .descending)), Fixtures.dDoubleFlat3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .descending)), Fixtures.cSharp3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .descending)), Fixtures.c3)
        assertEqual(Fixtures.c4.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .descending)), Fixtures.cFlat3)
    }

    @Test
    func transposeDescSuccess2() {
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.e6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .descending)), Fixtures.eFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished2, direction: .same)), Fixtures.dDoubleSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .descending)), Fixtures.dSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .descending)), Fixtures.d6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .descending)), Fixtures.dFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .descending)), Fixtures.cDoubleSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .descending)), Fixtures.cSharp6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .descending)), Fixtures.c6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .descending)), Fixtures.cFlat6)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .descending)), Fixtures.bSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .descending)), Fixtures.b5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .descending)), Fixtures.bFlat5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .descending)), Fixtures.aSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .descending)), Fixtures.a5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .descending)), Fixtures.aFlat5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .descending)), Fixtures.gDoubleSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .descending)), Fixtures.gSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .descending)), Fixtures.g5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .descending)), Fixtures.gFlat5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .descending)), Fixtures.fDoubleSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .descending)), Fixtures.fSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .descending)), Fixtures.f5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented7, direction: .descending)), Fixtures.fFlat5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .descending)), Fixtures.eSharp5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .descending)), Fixtures.e5)
        assertEqual(Fixtures.e6.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .descending)), Fixtures.eFlat5)
    }

    @Test
    func transposeDescSuccess3() {
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect1, direction: .same)), Fixtures.aFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented1, direction: .descending)), Fixtures.aDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished2, direction: .same)), Fixtures.gSharp2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor2, direction: .descending)), Fixtures.g2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major2, direction: .descending)), Fixtures.gFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented2, direction: .descending)), Fixtures.gDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished3, direction: .descending)), Fixtures.fSharp2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor3, direction: .descending)), Fixtures.f2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major3, direction: .descending)), Fixtures.fFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented3, direction: .descending)), Fixtures.fDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished4, direction: .descending)), Fixtures.e2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect4, direction: .descending)), Fixtures.eFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented4, direction: .descending)), Fixtures.eDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished5, direction: .descending)), Fixtures.d2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect5, direction: .descending)), Fixtures.dFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented5, direction: .descending)), Fixtures.dDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished6, direction: .descending)), Fixtures.cSharp2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor6, direction: .descending)), Fixtures.c2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major6, direction: .descending)), Fixtures.cFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented6, direction: .descending)), Fixtures.cDoubleFlat2)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished7, direction: .descending)), Fixtures.b1)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.minor7, direction: .descending)), Fixtures.bFlat1)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.major7, direction: .descending)), Fixtures.bDoubleFlat1)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.diminished8, direction: .descending)), Fixtures.a1)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.perfect8, direction: .descending)), Fixtures.aFlat1)
        assertEqual(Fixtures.aFlat2.transposed(by: DirectedInterval(interval: Fixtures.augmented8, direction: .descending)), Fixtures.aDoubleFlat1)
    }
}
