// © 2025–2026 John Gary Pusey (see LICENSE.md)

@testable import IvorTuning
import Testing

// swiftlint:disable file_length

struct PitchTests {
}

// MARK: -

extension PitchTests {
    @Test
    func intervalFailure() {
    }

    @Test
    func intervalSuccess1() {
        assertEqual(Pitch.c4.interval(to: .c4), (.perfect1, .same))
        assertEqual(Pitch.c4.interval(to: .cSharp4), (.augmented1, .ascending))
        assertEqual(Pitch.c4.interval(to: .dDoubleFlat4), (.diminished2, .ascending))
        assertEqual(Pitch.c4.interval(to: .dFlat4), (.minor2, .ascending))
        assertEqual(Pitch.c4.interval(to: .d4), (.major2, .ascending))
        assertEqual(Pitch.c4.interval(to: .dSharp4), (.augmented2, .ascending))
        assertEqual(Pitch.c4.interval(to: .eDoubleFlat4), (.diminished3, .ascending))
        assertEqual(Pitch.c4.interval(to: .eFlat4), (.minor3, .ascending))
        assertEqual(Pitch.c4.interval(to: .e4), (.major3, .ascending))
        assertEqual(Pitch.c4.interval(to: .eSharp4), (.augmented3, .ascending))
        assertEqual(Pitch.c4.interval(to: .fDoubleFlat4), (.doublyDiminished4, .ascending))
        assertEqual(Pitch.c4.interval(to: .fFlat4), (.diminished4, .ascending))
        assertEqual(Pitch.c4.interval(to: .f4), (.perfect4, .ascending))
        assertEqual(Pitch.c4.interval(to: .fSharp4), (.augmented4, .ascending))
        assertEqual(Pitch.c4.interval(to: .gFlat4), (.diminished5, .ascending))
        assertEqual(Pitch.c4.interval(to: .g4), (.perfect5, .ascending))
        assertEqual(Pitch.c4.interval(to: .gSharp4), (.augmented5, .ascending))
        assertEqual(Pitch.c4.interval(to: .aDoubleFlat4), (.diminished6, .ascending))
        assertEqual(Pitch.c4.interval(to: .aFlat4), (.minor6, .ascending))
        assertEqual(Pitch.c4.interval(to: .a4), (.major6, .ascending))
        assertEqual(Pitch.c4.interval(to: .aSharp4), (.augmented6, .ascending))
        assertEqual(Pitch.c4.interval(to: .bDoubleFlat4), (.diminished7, .ascending))
        assertEqual(Pitch.c4.interval(to: .bFlat4), (.minor7, .ascending))
        assertEqual(Pitch.c4.interval(to: .b4), (.major7, .ascending))
        assertEqual(Pitch.c4.interval(to: .bSharp4), (.augmented7, .ascending))
        assertEqual(Pitch.c4.interval(to: .cDoubleFlat5), (.doublyDiminished8, .ascending))
        assertEqual(Pitch.c4.interval(to: .cFlat5), (.diminished8, .ascending))
        assertEqual(Pitch.c4.interval(to: .c5), (.perfect8, .ascending))
        assertEqual(Pitch.c4.interval(to: .cSharp5), (.augmented8, .ascending))
        assertEqual(Pitch.c4.interval(to: .dDoubleFlat5), (.diminished9, .ascending))
        assertEqual(Pitch.c4.interval(to: .dFlat5), (.minor9, .ascending))
        assertEqual(Pitch.c4.interval(to: .d5), (.major9, .ascending))
        assertEqual(Pitch.c4.interval(to: .dSharp5), (.augmented9, .ascending))
        assertEqual(Pitch.c4.interval(to: .eDoubleFlat5), (.diminished10, .ascending))
        assertEqual(Pitch.c4.interval(to: .eFlat5), (.minor10, .ascending))
        assertEqual(Pitch.c4.interval(to: .e5), (.major10, .ascending))
        assertEqual(Pitch.c4.interval(to: .eSharp5), (.augmented10, .ascending))
        assertEqual(Pitch.c4.interval(to: .fDoubleFlat5), (.doublyDiminished11, .ascending))
        assertEqual(Pitch.c4.interval(to: .fFlat5), (.diminished11, .ascending))
        assertEqual(Pitch.c4.interval(to: .f5), (.perfect11, .ascending))
        assertEqual(Pitch.c4.interval(to: .fSharp5), (.augmented11, .ascending))
        assertEqual(Pitch.c4.interval(to: .gFlat5), (.diminished12, .ascending))
        assertEqual(Pitch.c4.interval(to: .g5), (.perfect12, .ascending))
        assertEqual(Pitch.c4.interval(to: .gSharp5), (.augmented12, .ascending))
        assertEqual(Pitch.c4.interval(to: .aDoubleFlat5), (.diminished13, .ascending))
        assertEqual(Pitch.c4.interval(to: .aFlat5), (.minor13, .ascending))
        assertEqual(Pitch.c4.interval(to: .a5), (.major13, .ascending))
        assertEqual(Pitch.c4.interval(to: .aSharp5), (.augmented13, .ascending))
        assertEqual(Pitch.c4.interval(to: .bDoubleFlat5), (.diminished14, .ascending))
        assertEqual(Pitch.c4.interval(to: .bFlat5), (.minor14, .ascending))
        assertEqual(Pitch.c4.interval(to: .b5), (.major14, .ascending))
        assertEqual(Pitch.c4.interval(to: .bSharp5), (.augmented14, .ascending))
        assertEqual(Pitch.c4.interval(to: .cDoubleFlat6), (.doublyDiminished15, .ascending))
        assertEqual(Pitch.c4.interval(to: .cFlat6), (.diminished15, .ascending))
        assertEqual(Pitch.c4.interval(to: .c6), (.perfect15, .ascending))
        assertEqual(Pitch.c4.interval(to: .cSharp6), (.augmented15, .ascending))

        assertEqual(Pitch.cDoubleFlat4.interval(to: .cDoubleSharp4), (.quadruplyAugmented1, .ascending))
    }

    @Test
    func intervalSuccess2() {
        assertEqual(Pitch.e6.interval(to: .e6), (.perfect1, .same))
        assertEqual(Pitch.e6.interval(to: .eSharp6), (.augmented1, .ascending))
        assertEqual(Pitch.e6.interval(to: .fFlat6), (.diminished2, .ascending))
        assertEqual(Pitch.e6.interval(to: .f6), (.minor2, .ascending))
        assertEqual(Pitch.e6.interval(to: .fSharp6), (.major2, .ascending))
        assertEqual(Pitch.e6.interval(to: .fDoubleSharp6), (.augmented2, .ascending))
        assertEqual(Pitch.e6.interval(to: .gFlat6), (.diminished3, .ascending))
        assertEqual(Pitch.e6.interval(to: .g6), (.minor3, .ascending))
        assertEqual(Pitch.e6.interval(to: .gSharp6), (.major3, .ascending))
        assertEqual(Pitch.e6.interval(to: .gDoubleSharp6), (.augmented3, .ascending))
        assertEqual(Pitch.e6.interval(to: .aFlat6), (.diminished4, .ascending))
        assertEqual(Pitch.e6.interval(to: .a6), (.perfect4, .ascending))
        assertEqual(Pitch.e6.interval(to: .aSharp6), (.augmented4, .ascending))
        assertEqual(Pitch.e6.interval(to: .bFlat6), (.diminished5, .ascending))
        assertEqual(Pitch.e6.interval(to: .b6), (.perfect5, .ascending))
        assertEqual(Pitch.e6.interval(to: .bSharp6), (.augmented5, .ascending))
        assertEqual(Pitch.e6.interval(to: .cFlat7), (.diminished6, .ascending))
        assertEqual(Pitch.e6.interval(to: .c7), (.minor6, .ascending))
        assertEqual(Pitch.e6.interval(to: .cSharp7), (.major6, .ascending))
        assertEqual(Pitch.e6.interval(to: .cDoubleSharp7), (.augmented6, .ascending))
        assertEqual(Pitch.e6.interval(to: .dFlat7), (.diminished7, .ascending))
        assertEqual(Pitch.e6.interval(to: .d7), (.minor7, .ascending))
        assertEqual(Pitch.e6.interval(to: .dSharp7), (.major7, .ascending))
        assertEqual(Pitch.e6.interval(to: .dDoubleSharp7), (.augmented7, .ascending))
        assertEqual(Pitch.e6.interval(to: .eFlat7), (.diminished8, .ascending))
        assertEqual(Pitch.e6.interval(to: .e7), (.perfect8, .ascending))
        assertEqual(Pitch.e6.interval(to: .eSharp7), (.augmented8, .ascending))
        assertEqual(Pitch.e6.interval(to: .fFlat7), (.diminished9, .ascending))
        assertEqual(Pitch.e6.interval(to: .f7), (.minor9, .ascending))
        assertEqual(Pitch.e6.interval(to: .fSharp7), (.major9, .ascending))
        assertEqual(Pitch.e6.interval(to: .fDoubleSharp7), (.augmented9, .ascending))
        assertEqual(Pitch.e6.interval(to: .gFlat7), (.diminished10, .ascending))
        assertEqual(Pitch.e6.interval(to: .g7), (.minor10, .ascending))
        assertEqual(Pitch.e6.interval(to: .gSharp7), (.major10, .ascending))
        assertEqual(Pitch.e6.interval(to: .gDoubleSharp7), (.augmented10, .ascending))
        assertEqual(Pitch.e6.interval(to: .aFlat7), (.diminished11, .ascending))
        assertEqual(Pitch.e6.interval(to: .a7), (.perfect11, .ascending))
        assertEqual(Pitch.e6.interval(to: .aSharp7), (.augmented11, .ascending))
        assertEqual(Pitch.e6.interval(to: .bFlat7), (.diminished12, .ascending))
        assertEqual(Pitch.e6.interval(to: .b7), (.perfect12, .ascending))
        assertEqual(Pitch.e6.interval(to: .bSharp7), (.augmented12, .ascending))
        assertEqual(Pitch.e6.interval(to: .cFlat8), (.diminished13, .ascending))
        assertEqual(Pitch.e6.interval(to: .c8), (.minor13, .ascending))
        assertEqual(Pitch.e6.interval(to: .cSharp8), (.major13, .ascending))
        assertEqual(Pitch.e6.interval(to: .cDoubleSharp8), (.augmented13, .ascending))
        assertEqual(Pitch.e6.interval(to: .dFlat8), (.diminished14, .ascending))
        assertEqual(Pitch.e6.interval(to: .d8), (.minor14, .ascending))
        assertEqual(Pitch.e6.interval(to: .dSharp8), (.major14, .ascending))
        assertEqual(Pitch.e6.interval(to: .dDoubleSharp8), (.augmented14, .ascending))
        assertEqual(Pitch.e6.interval(to: .eFlat8), (.diminished15, .ascending))
        assertEqual(Pitch.e6.interval(to: .e8), (.perfect15, .ascending))
        assertEqual(Pitch.e6.interval(to: .eSharp8), (.augmented15, .ascending))
    }

    @Test
    func intervalSuccess3() {
        assertEqual(Pitch.aFlat2.interval(to: .aFlat2), (.perfect1, .same))
        assertEqual(Pitch.aFlat2.interval(to: .a2), (.augmented1, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .bDoubleFlat2), (.minor2, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .bFlat2), (.major2, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .b2), (.augmented2, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cDoubleFlat3), (.diminished3, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cFlat3), (.minor3, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .c3), (.major3, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cSharp3), (.augmented3, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .dDoubleFlat3), (.diminished4, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .dFlat3), (.perfect4, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .d3), (.augmented4, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .eDoubleFlat3), (.diminished5, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .eFlat3), (.perfect5, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .e3), (.augmented5, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fDoubleFlat3), (.diminished6, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fFlat3), (.minor6, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .f3), (.major6, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fSharp3), (.augmented6, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gDoubleFlat3), (.diminished7, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gFlat3), (.minor7, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .g3), (.major7, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gSharp3), (.augmented7, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .aDoubleFlat3), (.diminished8, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .aFlat3), (.perfect8, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .a3), (.augmented8, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .bDoubleFlat3), (.minor9, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .bFlat3), (.major9, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .b3), (.augmented9, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cDoubleFlat4), (.diminished10, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cFlat4), (.minor10, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .c4), (.major10, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .cSharp4), (.augmented10, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .dDoubleFlat4), (.diminished11, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .dFlat4), (.perfect11, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .d4), (.augmented11, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .eDoubleFlat4), (.diminished12, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .eFlat4), (.perfect12, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .e4), (.augmented12, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fDoubleFlat4), (.diminished13, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fFlat4), (.minor13, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .f4), (.major13, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .fSharp4), (.augmented13, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gDoubleFlat4), (.diminished14, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gFlat4), (.minor14, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .g4), (.major14, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .gSharp4), (.augmented14, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .aDoubleFlat4), (.diminished15, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .aFlat4), (.perfect15, .ascending))
        assertEqual(Pitch.aFlat2.interval(to: .a4), (.augmented15, .ascending))
    }

    @Test
    func intervalSuccess4() {
        assertEqual(Pitch.c4.interval(to: .c4), (.perfect1, .same))
        assertEqual(Pitch.c4.interval(to: .cFlat4), (.augmented1, .descending))
        assertEqual(Pitch.c4.interval(to: .cDoubleFlat4), (.doublyAugmented1, .descending))
        assertEqual(Pitch.c4.interval(to: .bSharp3), (.diminished2, .descending))
        assertEqual(Pitch.c4.interval(to: .b3), (.minor2, .descending))
        assertEqual(Pitch.c4.interval(to: .bFlat3), (.major2, .descending))
        assertEqual(Pitch.c4.interval(to: .bDoubleFlat3), (.augmented2, .descending))
        assertEqual(Pitch.c4.interval(to: .aSharp3), (.diminished3, .descending))
        assertEqual(Pitch.c4.interval(to: .a3), (.minor3, .descending))
        assertEqual(Pitch.c4.interval(to: .aFlat3), (.major3, .descending))
        assertEqual(Pitch.c4.interval(to: .aDoubleFlat3), (.augmented3, .descending))
        assertEqual(Pitch.c4.interval(to: .gSharp3), (.diminished4, .descending))
        assertEqual(Pitch.c4.interval(to: .g3), (.perfect4, .descending))
        assertEqual(Pitch.c4.interval(to: .gFlat3), (.augmented4, .descending))
        assertEqual(Pitch.c4.interval(to: .fSharp3), (.diminished5, .descending))
        assertEqual(Pitch.c4.interval(to: .f3), (.perfect5, .descending))
        assertEqual(Pitch.c4.interval(to: .fFlat3), (.augmented5, .descending))
        assertEqual(Pitch.c4.interval(to: .eSharp3), (.diminished6, .descending))
        assertEqual(Pitch.c4.interval(to: .e3), (.minor6, .descending))
        assertEqual(Pitch.c4.interval(to: .eFlat3), (.major6, .descending))
        assertEqual(Pitch.c4.interval(to: .eDoubleFlat3), (.augmented6, .descending))
        assertEqual(Pitch.c4.interval(to: .dSharp3), (.diminished7, .descending))
        assertEqual(Pitch.c4.interval(to: .d3), (.minor7, .descending))
        assertEqual(Pitch.c4.interval(to: .dFlat3), (.major7, .descending))
        assertEqual(Pitch.c4.interval(to: .dDoubleFlat3), (.augmented7, .descending))
        assertEqual(Pitch.c4.interval(to: .cSharp3), (.diminished8, .descending))
        assertEqual(Pitch.c4.interval(to: .c3), (.perfect8, .descending))
        assertEqual(Pitch.c4.interval(to: .cFlat3), (.augmented8, .descending))
        assertEqual(Pitch.c4.interval(to: .bSharp2), (.diminished9, .descending))
        assertEqual(Pitch.c4.interval(to: .b2), (.minor9, .descending))
        assertEqual(Pitch.c4.interval(to: .bFlat2), (.major9, .descending))
        assertEqual(Pitch.c4.interval(to: .bDoubleFlat2), (.augmented9, .descending))
        assertEqual(Pitch.c4.interval(to: .aSharp2), (.diminished10, .descending))
        assertEqual(Pitch.c4.interval(to: .a2), (.minor10, .descending))
        assertEqual(Pitch.c4.interval(to: .aFlat2), (.major10, .descending))
        assertEqual(Pitch.c4.interval(to: .aDoubleFlat2), (.augmented10, .descending))
        assertEqual(Pitch.c4.interval(to: .gSharp2), (.diminished11, .descending))
        assertEqual(Pitch.c4.interval(to: .g2), (.perfect11, .descending))
        assertEqual(Pitch.c4.interval(to: .gFlat2), (.augmented11, .descending))
        assertEqual(Pitch.c4.interval(to: .fSharp2), (.diminished12, .descending))
        assertEqual(Pitch.c4.interval(to: .f2), (.perfect12, .descending))
        assertEqual(Pitch.c4.interval(to: .fFlat2), (.augmented12, .descending))
        assertEqual(Pitch.c4.interval(to: .eSharp2), (.diminished13, .descending))
        assertEqual(Pitch.c4.interval(to: .e2), (.minor13, .descending))
        assertEqual(Pitch.c4.interval(to: .eFlat2), (.major13, .descending))
        assertEqual(Pitch.c4.interval(to: .eDoubleFlat2), (.augmented13, .descending))
        assertEqual(Pitch.c4.interval(to: .dSharp2), (.diminished14, .descending))
        assertEqual(Pitch.c4.interval(to: .d2), (.minor14, .descending))
        assertEqual(Pitch.c4.interval(to: .dFlat2), (.major14, .descending))
        assertEqual(Pitch.c4.interval(to: .dDoubleFlat2), (.augmented14, .descending))
        assertEqual(Pitch.c4.interval(to: .cSharp2), (.diminished15, .descending))
        assertEqual(Pitch.c4.interval(to: .c2), (.perfect15, .descending))
        assertEqual(Pitch.c4.interval(to: .cFlat2), (.augmented15, .descending))
    }

    @Test
    func intervalSuccess5() {
        assertEqual(Pitch.e6.interval(to: .e6), (.perfect1, .same))
        assertEqual(Pitch.e6.interval(to: .eFlat6), (.augmented1, .descending))
        assertEqual(Pitch.e6.interval(to: .dDoubleSharp6), (.diminished2, .descending))
        assertEqual(Pitch.e6.interval(to: .dSharp6), (.minor2, .descending))
        assertEqual(Pitch.e6.interval(to: .d6), (.major2, .descending))
        assertEqual(Pitch.e6.interval(to: .dFlat6), (.augmented2, .descending))
        assertEqual(Pitch.e6.interval(to: .cDoubleSharp6), (.diminished3, .descending))
        assertEqual(Pitch.e6.interval(to: .cSharp6), (.minor3, .descending))
        assertEqual(Pitch.e6.interval(to: .c6), (.major3, .descending))
        assertEqual(Pitch.e6.interval(to: .cFlat6), (.augmented3, .descending))
        assertEqual(Pitch.e6.interval(to: .bSharp5), (.diminished4, .descending))
        assertEqual(Pitch.e6.interval(to: .b5), (.perfect4, .descending))
        assertEqual(Pitch.e6.interval(to: .bFlat5), (.augmented4, .descending))
        assertEqual(Pitch.e6.interval(to: .aSharp5), (.diminished5, .descending))
        assertEqual(Pitch.e6.interval(to: .a5), (.perfect5, .descending))
        assertEqual(Pitch.e6.interval(to: .aFlat5), (.augmented5, .descending))
        assertEqual(Pitch.e6.interval(to: .gDoubleSharp5), (.diminished6, .descending))
        assertEqual(Pitch.e6.interval(to: .gSharp5), (.minor6, .descending))
        assertEqual(Pitch.e6.interval(to: .g5), (.major6, .descending))
        assertEqual(Pitch.e6.interval(to: .gFlat5), (.augmented6, .descending))
        assertEqual(Pitch.e6.interval(to: .fDoubleSharp5), (.diminished7, .descending))
        assertEqual(Pitch.e6.interval(to: .fSharp5), (.minor7, .descending))
        assertEqual(Pitch.e6.interval(to: .f5), (.major7, .descending))
        assertEqual(Pitch.e6.interval(to: .fFlat5), (.augmented7, .descending))
        assertEqual(Pitch.e6.interval(to: .eSharp5), (.diminished8, .descending))
        assertEqual(Pitch.e6.interval(to: .e5), (.perfect8, .descending))
        assertEqual(Pitch.e6.interval(to: .eFlat5), (.augmented8, .descending))
        assertEqual(Pitch.e6.interval(to: .dDoubleSharp5), (.diminished9, .descending))
        assertEqual(Pitch.e6.interval(to: .dSharp5), (.minor9, .descending))
        assertEqual(Pitch.e6.interval(to: .d5), (.major9, .descending))
        assertEqual(Pitch.e6.interval(to: .dFlat5), (.augmented9, .descending))
        assertEqual(Pitch.e6.interval(to: .cDoubleSharp5), (.diminished10, .descending))
        assertEqual(Pitch.e6.interval(to: .cSharp5), (.minor10, .descending))
        assertEqual(Pitch.e6.interval(to: .c5), (.major10, .descending))
        assertEqual(Pitch.e6.interval(to: .cFlat5), (.augmented10, .descending))
        assertEqual(Pitch.e6.interval(to: .bSharp4), (.diminished11, .descending))
        assertEqual(Pitch.e6.interval(to: .b4), (.perfect11, .descending))
        assertEqual(Pitch.e6.interval(to: .bFlat4), (.augmented11, .descending))
        assertEqual(Pitch.e6.interval(to: .aSharp4), (.diminished12, .descending))
        assertEqual(Pitch.e6.interval(to: .a4), (.perfect12, .descending))
        assertEqual(Pitch.e6.interval(to: .aFlat4), (.augmented12, .descending))
        assertEqual(Pitch.e6.interval(to: .gDoubleSharp4), (.diminished13, .descending))
        assertEqual(Pitch.e6.interval(to: .gSharp4), (.minor13, .descending))
        assertEqual(Pitch.e6.interval(to: .g4), (.major13, .descending))
        assertEqual(Pitch.e6.interval(to: .gFlat4), (.augmented13, .descending))
        assertEqual(Pitch.e6.interval(to: .fDoubleSharp4), (.diminished14, .descending))
        assertEqual(Pitch.e6.interval(to: .fSharp4), (.minor14, .descending))
        assertEqual(Pitch.e6.interval(to: .f4), (.major14, .descending))
        assertEqual(Pitch.e6.interval(to: .fFlat4), (.augmented14, .descending))
        assertEqual(Pitch.e6.interval(to: .eSharp4), (.diminished15, .descending))
        assertEqual(Pitch.e6.interval(to: .e4), (.perfect15, .descending))
        assertEqual(Pitch.e6.interval(to: .eFlat4), (.augmented15, .descending))
    }

    @Test
    func intervalSuccess6() {
        assertEqual(Pitch.aFlat2.interval(to: .aFlat2), (.perfect1, .same))
        assertEqual(Pitch.aFlat2.interval(to: .aDoubleFlat2), (.augmented1, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gSharp2), (.diminished2, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .g2), (.minor2, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gFlat2), (.major2, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gDoubleFlat2), (.augmented2, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fSharp2), (.diminished3, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .f2), (.minor3, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fFlat2), (.major3, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fDoubleFlat2), (.augmented3, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .e2), (.diminished4, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .eFlat2), (.perfect4, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .eDoubleFlat2), (.augmented4, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .d2), (.diminished5, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .dFlat2), (.perfect5, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .dDoubleFlat2), (.augmented5, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cSharp2), (.diminished6, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .c2), (.minor6, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cFlat2), (.major6, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cDoubleFlat2), (.augmented6, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .b1), (.diminished7, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .bFlat1), (.minor7, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .bDoubleFlat1), (.major7, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .a1), (.diminished8, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .aFlat1), (.perfect8, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .aDoubleFlat1), (.augmented8, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gSharp1), (.diminished9, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .g1), (.minor9, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gFlat1), (.major9, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .gDoubleFlat1), (.augmented9, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fSharp1), (.diminished10, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .f1), (.minor10, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fFlat1), (.major10, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .fDoubleFlat1), (.augmented10, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .e1), (.diminished11, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .eFlat1), (.perfect11, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .eDoubleFlat1), (.augmented11, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .d1), (.diminished12, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .dFlat1), (.perfect12, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .dDoubleFlat1), (.augmented12, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cSharp1), (.diminished13, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .c1), (.minor13, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cFlat1), (.major13, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .cDoubleFlat1), (.augmented13, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .b0), (.diminished14, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .bFlat0), (.minor14, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .bDoubleFlat0), (.major14, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .a0), (.diminished15, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .aFlat0), (.perfect15, .descending))
        assertEqual(Pitch.aFlat2.interval(to: .aDoubleFlat0), (.augmented15, .descending))
    }

    @Test
    func transposeAscFailure() {
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished2, direction: .ascending)) == nil)
    }

    @Test
    func transposeAscSuccess1() {
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .c4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented1, direction: .ascending)) == .cSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished2, direction: .ascending)) == .dDoubleFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor2, direction: .ascending)) == .dFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major2, direction: .ascending)) == .d4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented2, direction: .ascending)) == .dSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished3, direction: .ascending)) == .eDoubleFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor3, direction: .ascending)) == .eFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major3, direction: .ascending)) == .e4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented3, direction: .ascending)) == .eSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished4, direction: .ascending)) == .fFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect4, direction: .ascending)) == .f4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented4, direction: .ascending)) == .fSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished5, direction: .ascending)) == .gFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect5, direction: .ascending)) == .g4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented5, direction: .ascending)) == .gSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished6, direction: .ascending)) == .aDoubleFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor6, direction: .ascending)) == .aFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major6, direction: .ascending)) == .a4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented6, direction: .ascending)) == .aSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished7, direction: .ascending)) == .bDoubleFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor7, direction: .ascending)) == .bFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major7, direction: .ascending)) == .b4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented7, direction: .ascending)) == .bSharp4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished8, direction: .ascending)) == .cFlat5)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect8, direction: .ascending)) == .c5)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented8, direction: .ascending)) == .cSharp5)
    }

    @Test
    func transposeAscSuccess2() {
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .e6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented1, direction: .ascending)) == .eSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished2, direction: .ascending)) == .fFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor2, direction: .ascending)) == .f6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major2, direction: .ascending)) == .fSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented2, direction: .ascending)) == .fDoubleSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished3, direction: .ascending)) == .gFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor3, direction: .ascending)) == .g6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major3, direction: .ascending)) == .gSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented3, direction: .ascending)) == .gDoubleSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished4, direction: .ascending)) == .aFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect4, direction: .ascending)) == .a6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented4, direction: .ascending)) == .aSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished5, direction: .ascending)) == .bFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect5, direction: .ascending)) == .b6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented5, direction: .ascending)) == .bSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished6, direction: .ascending)) == .cFlat7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor6, direction: .ascending)) == .c7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major6, direction: .ascending)) == .cSharp7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented6, direction: .ascending)) == .cDoubleSharp7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished7, direction: .ascending)) == .dFlat7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor7, direction: .ascending)) == .d7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major7, direction: .ascending)) == .dSharp7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented7, direction: .ascending)) == .dDoubleSharp7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished8, direction: .ascending)) == .eFlat7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect8, direction: .ascending)) == .e7)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented8, direction: .ascending)) == .eSharp7)
    }

    @Test
    func transposeAscSuccess3() {
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .aFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented1, direction: .ascending)) == .a2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor2, direction: .ascending)) == .bDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major2, direction: .ascending)) == .bFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented2, direction: .ascending)) == .b2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished3, direction: .ascending)) == .cDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor3, direction: .ascending)) == .cFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major3, direction: .ascending)) == .c3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented3, direction: .ascending)) == .cSharp3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished4, direction: .ascending)) == .dDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect4, direction: .ascending)) == .dFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented4, direction: .ascending)) == .d3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished5, direction: .ascending)) == .eDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect5, direction: .ascending)) == .eFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented5, direction: .ascending)) == .e3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished6, direction: .ascending)) == .fDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor6, direction: .ascending)) == .fFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major6, direction: .ascending)) == .f3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented6, direction: .ascending)) == .fSharp3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished7, direction: .ascending)) == .gDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor7, direction: .ascending)) == .gFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major7, direction: .ascending)) == .g3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented7, direction: .ascending)) == .gSharp3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished8, direction: .ascending)) == .aDoubleFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect8, direction: .ascending)) == .aFlat3)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented8, direction: .ascending)) == .a3)
    }

    @Test
    func transposeDescFailure() {
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented7, direction: .descending)) == nil)
    }

    @Test
    func transposeDescSuccess1() {
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .c4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented1, direction: .descending)) == .cFlat4)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished2, direction: .descending)) == .bSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor2, direction: .descending)) == .b3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major2, direction: .descending)) == .bFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented2, direction: .descending)) == .bDoubleFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished3, direction: .descending)) == .aSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor3, direction: .descending)) == .a3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major3, direction: .descending)) == .aFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented3, direction: .descending)) == .aDoubleFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished4, direction: .descending)) == .gSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect4, direction: .descending)) == .g3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented4, direction: .descending)) == .gFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished5, direction: .descending)) == .fSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect5, direction: .descending)) == .f3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented5, direction: .descending)) == .fFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished6, direction: .descending)) == .eSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor6, direction: .descending)) == .e3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major6, direction: .descending)) == .eFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented6, direction: .descending)) == .eDoubleFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished7, direction: .descending)) == .dSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .minor7, direction: .descending)) == .d3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .major7, direction: .descending)) == .dFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented7, direction: .descending)) == .dDoubleFlat3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .diminished8, direction: .descending)) == .cSharp3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .perfect8, direction: .descending)) == .c3)
        #expect(Pitch.c4.transposed(by: DirectedInterval(interval: .augmented8, direction: .descending)) == .cFlat3)
    }

    @Test
    func transposeDescSuccess2() {
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .e6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented1, direction: .descending)) == .eFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished2, direction: .descending)) == .dDoubleSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor2, direction: .descending)) == .dSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major2, direction: .descending)) == .d6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented2, direction: .descending)) == .dFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished3, direction: .descending)) == .cDoubleSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor3, direction: .descending)) == .cSharp6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major3, direction: .descending)) == .c6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented3, direction: .descending)) == .cFlat6)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished4, direction: .descending)) == .bSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect4, direction: .descending)) == .b5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented4, direction: .descending)) == .bFlat5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished5, direction: .descending)) == .aSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect5, direction: .descending)) == .a5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented5, direction: .descending)) == .aFlat5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished6, direction: .descending)) == .gDoubleSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor6, direction: .descending)) == .gSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major6, direction: .descending)) == .g5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented6, direction: .descending)) == .gFlat5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished7, direction: .descending)) == .fDoubleSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .minor7, direction: .descending)) == .fSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .major7, direction: .descending)) == .f5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented7, direction: .descending)) == .fFlat5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .diminished8, direction: .descending)) == .eSharp5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .perfect8, direction: .descending)) == .e5)
        #expect(Pitch.e6.transposed(by: DirectedInterval(interval: .augmented8, direction: .descending)) == .eFlat5)
    }

    @Test
    func transposeDescSuccess3() {
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect1, direction: .same)) == .aFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented1, direction: .descending)) == .aDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished2, direction: .descending)) == .gSharp2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor2, direction: .descending)) == .g2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major2, direction: .descending)) == .gFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented2, direction: .descending)) == .gDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished3, direction: .descending)) == .fSharp2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor3, direction: .descending)) == .f2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major3, direction: .descending)) == .fFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented3, direction: .descending)) == .fDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished4, direction: .descending)) == .e2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect4, direction: .descending)) == .eFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented4, direction: .descending)) == .eDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished5, direction: .descending)) == .d2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect5, direction: .descending)) == .dFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented5, direction: .descending)) == .dDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished6, direction: .descending)) == .cSharp2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor6, direction: .descending)) == .c2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major6, direction: .descending)) == .cFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented6, direction: .descending)) == .cDoubleFlat2)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished7, direction: .descending)) == .b1)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .minor7, direction: .descending)) == .bFlat1)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .major7, direction: .descending)) == .bDoubleFlat1)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .diminished8, direction: .descending)) == .a1)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .perfect8, direction: .descending)) == .aFlat1)
        #expect(Pitch.aFlat2.transposed(by: DirectedInterval(interval: .augmented8, direction: .descending)) == .aDoubleFlat1)
    }
}
