// © 2025–2026 John Gary Pusey (see LICENSE.md)

import IvorTuning
import Testing

struct PitchCommonTests {
}

// MARK: -

extension PitchCommonTests {
    @Test
    func a_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.a0, .a, 0),
                                                   (.a1, .a, 1),
                                                   (.a2, .a, 2),
                                                   (.a3, .a, 3),
                                                   (.a4, .a, 4),
                                                   (.a5, .a, 5),
                                                   (.a6, .a, 6),
                                                   (.a7, .a, 7),
                                                   (.a8, .a, 8),
                                                   (.a9, .a, 9),
                                                   (.aDoubleFlat0, .aDoubleFlat, 0),
                                                   (.aDoubleFlat1, .aDoubleFlat, 1),
                                                   (.aDoubleFlat2, .aDoubleFlat, 2),
                                                   (.aDoubleFlat3, .aDoubleFlat, 3),
                                                   (.aDoubleFlat4, .aDoubleFlat, 4),
                                                   (.aDoubleFlat5, .aDoubleFlat, 5),
                                                   (.aDoubleFlat6, .aDoubleFlat, 6),
                                                   (.aDoubleFlat7, .aDoubleFlat, 7),
                                                   (.aDoubleFlat8, .aDoubleFlat, 8),
                                                   (.aDoubleFlat9, .aDoubleFlat, 9),
                                                   (.aDoubleSharp0, .aDoubleSharp, 0),
                                                   (.aDoubleSharp1, .aDoubleSharp, 1),
                                                   (.aDoubleSharp2, .aDoubleSharp, 2),
                                                   (.aDoubleSharp3, .aDoubleSharp, 3),
                                                   (.aDoubleSharp4, .aDoubleSharp, 4),
                                                   (.aDoubleSharp5, .aDoubleSharp, 5),
                                                   (.aDoubleSharp6, .aDoubleSharp, 6),
                                                   (.aDoubleSharp7, .aDoubleSharp, 7),
                                                   (.aDoubleSharp8, .aDoubleSharp, 8),
                                                   (.aDoubleSharp9, .aDoubleSharp, 9),
                                                   (.aFlat0, .aFlat, 0),
                                                   (.aFlat1, .aFlat, 1),
                                                   (.aFlat2, .aFlat, 2),
                                                   (.aFlat3, .aFlat, 3),
                                                   (.aFlat4, .aFlat, 4),
                                                   (.aFlat5, .aFlat, 5),
                                                   (.aFlat6, .aFlat, 6),
                                                   (.aFlat7, .aFlat, 7),
                                                   (.aFlat8, .aFlat, 8),
                                                   (.aFlat9, .aFlat, 9),
                                                   (.aSharp0, .aSharp, 0),
                                                   (.aSharp1, .aSharp, 1),
                                                   (.aSharp2, .aSharp, 2),
                                                   (.aSharp3, .aSharp, 3),
                                                   (.aSharp4, .aSharp, 4),
                                                   (.aSharp5, .aSharp, 5),
                                                   (.aSharp6, .aSharp, 6),
                                                   (.aSharp7, .aSharp, 7),
                                                   (.aSharp8, .aSharp, 8),
                                                   (.aSharp9, .aSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func b_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.b0, .b, 0),
                                                   (.b1, .b, 1),
                                                   (.b2, .b, 2),
                                                   (.b3, .b, 3),
                                                   (.b4, .b, 4),
                                                   (.b5, .b, 5),
                                                   (.b6, .b, 6),
                                                   (.b7, .b, 7),
                                                   (.b8, .b, 8),
                                                   (.b9, .b, 9),
                                                   (.bDoubleFlat0, .bDoubleFlat, 0),
                                                   (.bDoubleFlat1, .bDoubleFlat, 1),
                                                   (.bDoubleFlat2, .bDoubleFlat, 2),
                                                   (.bDoubleFlat3, .bDoubleFlat, 3),
                                                   (.bDoubleFlat4, .bDoubleFlat, 4),
                                                   (.bDoubleFlat5, .bDoubleFlat, 5),
                                                   (.bDoubleFlat6, .bDoubleFlat, 6),
                                                   (.bDoubleFlat7, .bDoubleFlat, 7),
                                                   (.bDoubleFlat8, .bDoubleFlat, 8),
                                                   (.bDoubleFlat9, .bDoubleFlat, 9),
                                                   (.bDoubleSharp0, .bDoubleSharp, 0),
                                                   (.bDoubleSharp1, .bDoubleSharp, 1),
                                                   (.bDoubleSharp2, .bDoubleSharp, 2),
                                                   (.bDoubleSharp3, .bDoubleSharp, 3),
                                                   (.bDoubleSharp4, .bDoubleSharp, 4),
                                                   (.bDoubleSharp5, .bDoubleSharp, 5),
                                                   (.bDoubleSharp6, .bDoubleSharp, 6),
                                                   (.bDoubleSharp7, .bDoubleSharp, 7),
                                                   (.bDoubleSharp8, .bDoubleSharp, 8),
                                                   (.bDoubleSharp9, .bDoubleSharp, 9),
                                                   (.bFlat0, .bFlat, 0),
                                                   (.bFlat1, .bFlat, 1),
                                                   (.bFlat2, .bFlat, 2),
                                                   (.bFlat3, .bFlat, 3),
                                                   (.bFlat4, .bFlat, 4),
                                                   (.bFlat5, .bFlat, 5),
                                                   (.bFlat6, .bFlat, 6),
                                                   (.bFlat7, .bFlat, 7),
                                                   (.bFlat8, .bFlat, 8),
                                                   (.bFlat9, .bFlat, 9),
                                                   (.bSharp0, .bSharp, 0),
                                                   (.bSharp1, .bSharp, 1),
                                                   (.bSharp2, .bSharp, 2),
                                                   (.bSharp3, .bSharp, 3),
                                                   (.bSharp4, .bSharp, 4),
                                                   (.bSharp5, .bSharp, 5),
                                                   (.bSharp6, .bSharp, 6),
                                                   (.bSharp7, .bSharp, 7),
                                                   (.bSharp8, .bSharp, 8),
                                                   (.bSharp9, .bSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func c_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.c0, .c, 0),
                                                   (.c1, .c, 1),
                                                   (.c2, .c, 2),
                                                   (.c3, .c, 3),
                                                   (.c4, .c, 4),
                                                   (.c5, .c, 5),
                                                   (.c6, .c, 6),
                                                   (.c7, .c, 7),
                                                   (.c8, .c, 8),
                                                   (.c9, .c, 9),
                                                   (.cDoubleFlat0, .cDoubleFlat, 0),
                                                   (.cDoubleFlat1, .cDoubleFlat, 1),
                                                   (.cDoubleFlat2, .cDoubleFlat, 2),
                                                   (.cDoubleFlat3, .cDoubleFlat, 3),
                                                   (.cDoubleFlat4, .cDoubleFlat, 4),
                                                   (.cDoubleFlat5, .cDoubleFlat, 5),
                                                   (.cDoubleFlat6, .cDoubleFlat, 6),
                                                   (.cDoubleFlat7, .cDoubleFlat, 7),
                                                   (.cDoubleFlat8, .cDoubleFlat, 8),
                                                   (.cDoubleFlat9, .cDoubleFlat, 9),
                                                   (.cDoubleSharp0, .cDoubleSharp, 0),
                                                   (.cDoubleSharp1, .cDoubleSharp, 1),
                                                   (.cDoubleSharp2, .cDoubleSharp, 2),
                                                   (.cDoubleSharp3, .cDoubleSharp, 3),
                                                   (.cDoubleSharp4, .cDoubleSharp, 4),
                                                   (.cDoubleSharp5, .cDoubleSharp, 5),
                                                   (.cDoubleSharp6, .cDoubleSharp, 6),
                                                   (.cDoubleSharp7, .cDoubleSharp, 7),
                                                   (.cDoubleSharp8, .cDoubleSharp, 8),
                                                   (.cDoubleSharp9, .cDoubleSharp, 9),
                                                   (.cFlat0, .cFlat, 0),
                                                   (.cFlat1, .cFlat, 1),
                                                   (.cFlat2, .cFlat, 2),
                                                   (.cFlat3, .cFlat, 3),
                                                   (.cFlat4, .cFlat, 4),
                                                   (.cFlat5, .cFlat, 5),
                                                   (.cFlat6, .cFlat, 6),
                                                   (.cFlat7, .cFlat, 7),
                                                   (.cFlat8, .cFlat, 8),
                                                   (.cFlat9, .cFlat, 9),
                                                   (.cSharp0, .cSharp, 0),
                                                   (.cSharp1, .cSharp, 1),
                                                   (.cSharp2, .cSharp, 2),
                                                   (.cSharp3, .cSharp, 3),
                                                   (.cSharp4, .cSharp, 4),
                                                   (.cSharp5, .cSharp, 5),
                                                   (.cSharp6, .cSharp, 6),
                                                   (.cSharp7, .cSharp, 7),
                                                   (.cSharp8, .cSharp, 8),
                                                   (.cSharp9, .cSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func d_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.d0, .d, 0),
                                                   (.d1, .d, 1),
                                                   (.d2, .d, 2),
                                                   (.d3, .d, 3),
                                                   (.d4, .d, 4),
                                                   (.d5, .d, 5),
                                                   (.d6, .d, 6),
                                                   (.d7, .d, 7),
                                                   (.d8, .d, 8),
                                                   (.d9, .d, 9),
                                                   (.dDoubleFlat0, .dDoubleFlat, 0),
                                                   (.dDoubleFlat1, .dDoubleFlat, 1),
                                                   (.dDoubleFlat2, .dDoubleFlat, 2),
                                                   (.dDoubleFlat3, .dDoubleFlat, 3),
                                                   (.dDoubleFlat4, .dDoubleFlat, 4),
                                                   (.dDoubleFlat5, .dDoubleFlat, 5),
                                                   (.dDoubleFlat6, .dDoubleFlat, 6),
                                                   (.dDoubleFlat7, .dDoubleFlat, 7),
                                                   (.dDoubleFlat8, .dDoubleFlat, 8),
                                                   (.dDoubleFlat9, .dDoubleFlat, 9),
                                                   (.dDoubleSharp0, .dDoubleSharp, 0),
                                                   (.dDoubleSharp1, .dDoubleSharp, 1),
                                                   (.dDoubleSharp2, .dDoubleSharp, 2),
                                                   (.dDoubleSharp3, .dDoubleSharp, 3),
                                                   (.dDoubleSharp4, .dDoubleSharp, 4),
                                                   (.dDoubleSharp5, .dDoubleSharp, 5),
                                                   (.dDoubleSharp6, .dDoubleSharp, 6),
                                                   (.dDoubleSharp7, .dDoubleSharp, 7),
                                                   (.dDoubleSharp8, .dDoubleSharp, 8),
                                                   (.dDoubleSharp9, .dDoubleSharp, 9),
                                                   (.dFlat0, .dFlat, 0),
                                                   (.dFlat1, .dFlat, 1),
                                                   (.dFlat2, .dFlat, 2),
                                                   (.dFlat3, .dFlat, 3),
                                                   (.dFlat4, .dFlat, 4),
                                                   (.dFlat5, .dFlat, 5),
                                                   (.dFlat6, .dFlat, 6),
                                                   (.dFlat7, .dFlat, 7),
                                                   (.dFlat8, .dFlat, 8),
                                                   (.dFlat9, .dFlat, 9),
                                                   (.dSharp0, .dSharp, 0),
                                                   (.dSharp1, .dSharp, 1),
                                                   (.dSharp2, .dSharp, 2),
                                                   (.dSharp3, .dSharp, 3),
                                                   (.dSharp4, .dSharp, 4),
                                                   (.dSharp5, .dSharp, 5),
                                                   (.dSharp6, .dSharp, 6),
                                                   (.dSharp7, .dSharp, 7),
                                                   (.dSharp8, .dSharp, 8),
                                                   (.dSharp9, .dSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func e_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.e0, .e, 0),
                                                   (.e1, .e, 1),
                                                   (.e2, .e, 2),
                                                   (.e3, .e, 3),
                                                   (.e4, .e, 4),
                                                   (.e5, .e, 5),
                                                   (.e6, .e, 6),
                                                   (.e7, .e, 7),
                                                   (.e8, .e, 8),
                                                   (.e9, .e, 9),
                                                   (.eDoubleFlat0, .eDoubleFlat, 0),
                                                   (.eDoubleFlat1, .eDoubleFlat, 1),
                                                   (.eDoubleFlat2, .eDoubleFlat, 2),
                                                   (.eDoubleFlat3, .eDoubleFlat, 3),
                                                   (.eDoubleFlat4, .eDoubleFlat, 4),
                                                   (.eDoubleFlat5, .eDoubleFlat, 5),
                                                   (.eDoubleFlat6, .eDoubleFlat, 6),
                                                   (.eDoubleFlat7, .eDoubleFlat, 7),
                                                   (.eDoubleFlat8, .eDoubleFlat, 8),
                                                   (.eDoubleFlat9, .eDoubleFlat, 9),
                                                   (.eDoubleSharp0, .eDoubleSharp, 0),
                                                   (.eDoubleSharp1, .eDoubleSharp, 1),
                                                   (.eDoubleSharp2, .eDoubleSharp, 2),
                                                   (.eDoubleSharp3, .eDoubleSharp, 3),
                                                   (.eDoubleSharp4, .eDoubleSharp, 4),
                                                   (.eDoubleSharp5, .eDoubleSharp, 5),
                                                   (.eDoubleSharp6, .eDoubleSharp, 6),
                                                   (.eDoubleSharp7, .eDoubleSharp, 7),
                                                   (.eDoubleSharp8, .eDoubleSharp, 8),
                                                   (.eDoubleSharp9, .eDoubleSharp, 9),
                                                   (.eFlat0, .eFlat, 0),
                                                   (.eFlat1, .eFlat, 1),
                                                   (.eFlat2, .eFlat, 2),
                                                   (.eFlat3, .eFlat, 3),
                                                   (.eFlat4, .eFlat, 4),
                                                   (.eFlat5, .eFlat, 5),
                                                   (.eFlat6, .eFlat, 6),
                                                   (.eFlat7, .eFlat, 7),
                                                   (.eFlat8, .eFlat, 8),
                                                   (.eFlat9, .eFlat, 9),
                                                   (.eSharp0, .eSharp, 0),
                                                   (.eSharp1, .eSharp, 1),
                                                   (.eSharp2, .eSharp, 2),
                                                   (.eSharp3, .eSharp, 3),
                                                   (.eSharp4, .eSharp, 4),
                                                   (.eSharp5, .eSharp, 5),
                                                   (.eSharp6, .eSharp, 6),
                                                   (.eSharp7, .eSharp, 7),
                                                   (.eSharp8, .eSharp, 8),
                                                   (.eSharp9, .eSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func f_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.f0, .f, 0),
                                                   (.f1, .f, 1),
                                                   (.f2, .f, 2),
                                                   (.f3, .f, 3),
                                                   (.f4, .f, 4),
                                                   (.f5, .f, 5),
                                                   (.f6, .f, 6),
                                                   (.f7, .f, 7),
                                                   (.f8, .f, 8),
                                                   (.f9, .f, 9),
                                                   (.fDoubleFlat0, .fDoubleFlat, 0),
                                                   (.fDoubleFlat1, .fDoubleFlat, 1),
                                                   (.fDoubleFlat2, .fDoubleFlat, 2),
                                                   (.fDoubleFlat3, .fDoubleFlat, 3),
                                                   (.fDoubleFlat4, .fDoubleFlat, 4),
                                                   (.fDoubleFlat5, .fDoubleFlat, 5),
                                                   (.fDoubleFlat6, .fDoubleFlat, 6),
                                                   (.fDoubleFlat7, .fDoubleFlat, 7),
                                                   (.fDoubleFlat8, .fDoubleFlat, 8),
                                                   (.fDoubleFlat9, .fDoubleFlat, 9),
                                                   (.fDoubleSharp0, .fDoubleSharp, 0),
                                                   (.fDoubleSharp1, .fDoubleSharp, 1),
                                                   (.fDoubleSharp2, .fDoubleSharp, 2),
                                                   (.fDoubleSharp3, .fDoubleSharp, 3),
                                                   (.fDoubleSharp4, .fDoubleSharp, 4),
                                                   (.fDoubleSharp5, .fDoubleSharp, 5),
                                                   (.fDoubleSharp6, .fDoubleSharp, 6),
                                                   (.fDoubleSharp7, .fDoubleSharp, 7),
                                                   (.fDoubleSharp8, .fDoubleSharp, 8),
                                                   (.fDoubleSharp9, .fDoubleSharp, 9),
                                                   (.fFlat0, .fFlat, 0),
                                                   (.fFlat1, .fFlat, 1),
                                                   (.fFlat2, .fFlat, 2),
                                                   (.fFlat3, .fFlat, 3),
                                                   (.fFlat4, .fFlat, 4),
                                                   (.fFlat5, .fFlat, 5),
                                                   (.fFlat6, .fFlat, 6),
                                                   (.fFlat7, .fFlat, 7),
                                                   (.fFlat8, .fFlat, 8),
                                                   (.fFlat9, .fFlat, 9),
                                                   (.fSharp0, .fSharp, 0),
                                                   (.fSharp1, .fSharp, 1),
                                                   (.fSharp2, .fSharp, 2),
                                                   (.fSharp3, .fSharp, 3),
                                                   (.fSharp4, .fSharp, 4),
                                                   (.fSharp5, .fSharp, 5),
                                                   (.fSharp6, .fSharp, 6),
                                                   (.fSharp7, .fSharp, 7),
                                                   (.fSharp8, .fSharp, 8),
                                                   (.fSharp9, .fSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }

    @Test
    func g_pitchClassesAndOctaves() {
        let entries: [(Pitch, PitchClass, Int)] = [(.g0, .g, 0),
                                                   (.g1, .g, 1),
                                                   (.g2, .g, 2),
                                                   (.g3, .g, 3),
                                                   (.g4, .g, 4),
                                                   (.g5, .g, 5),
                                                   (.g6, .g, 6),
                                                   (.g7, .g, 7),
                                                   (.g8, .g, 8),
                                                   (.g9, .g, 9),
                                                   (.gDoubleFlat0, .gDoubleFlat, 0),
                                                   (.gDoubleFlat1, .gDoubleFlat, 1),
                                                   (.gDoubleFlat2, .gDoubleFlat, 2),
                                                   (.gDoubleFlat3, .gDoubleFlat, 3),
                                                   (.gDoubleFlat4, .gDoubleFlat, 4),
                                                   (.gDoubleFlat5, .gDoubleFlat, 5),
                                                   (.gDoubleFlat6, .gDoubleFlat, 6),
                                                   (.gDoubleFlat7, .gDoubleFlat, 7),
                                                   (.gDoubleFlat8, .gDoubleFlat, 8),
                                                   (.gDoubleFlat9, .gDoubleFlat, 9),
                                                   (.gDoubleSharp0, .gDoubleSharp, 0),
                                                   (.gDoubleSharp1, .gDoubleSharp, 1),
                                                   (.gDoubleSharp2, .gDoubleSharp, 2),
                                                   (.gDoubleSharp3, .gDoubleSharp, 3),
                                                   (.gDoubleSharp4, .gDoubleSharp, 4),
                                                   (.gDoubleSharp5, .gDoubleSharp, 5),
                                                   (.gDoubleSharp6, .gDoubleSharp, 6),
                                                   (.gDoubleSharp7, .gDoubleSharp, 7),
                                                   (.gDoubleSharp8, .gDoubleSharp, 8),
                                                   (.gDoubleSharp9, .gDoubleSharp, 9),
                                                   (.gFlat0, .gFlat, 0),
                                                   (.gFlat1, .gFlat, 1),
                                                   (.gFlat2, .gFlat, 2),
                                                   (.gFlat3, .gFlat, 3),
                                                   (.gFlat4, .gFlat, 4),
                                                   (.gFlat5, .gFlat, 5),
                                                   (.gFlat6, .gFlat, 6),
                                                   (.gFlat7, .gFlat, 7),
                                                   (.gFlat8, .gFlat, 8),
                                                   (.gFlat9, .gFlat, 9),
                                                   (.gSharp0, .gSharp, 0),
                                                   (.gSharp1, .gSharp, 1),
                                                   (.gSharp2, .gSharp, 2),
                                                   (.gSharp3, .gSharp, 3),
                                                   (.gSharp4, .gSharp, 4),
                                                   (.gSharp5, .gSharp, 5),
                                                   (.gSharp6, .gSharp, 6),
                                                   (.gSharp7, .gSharp, 7),
                                                   (.gSharp8, .gSharp, 8),
                                                   (.gSharp9, .gSharp, 9)]

        for (pitch, pitchClass, octave) in entries {
            #expect(pitch.pitchClass == pitchClass)
            #expect(pitch.octave.intValue == octave)
        }
    }
}
